// Generated from supabase/migrations (baseline + user_settings): column names and defaults of every
// public table, so the fake PostgREST rejects unknown columns like the real one does.
export const NOW = '2026-10-08T10:00:00.000000+00:00';
export const TODAY = '2026-10-08';

export type Default = () => unknown;
let idCounter = 0;
/** Deterministic UUID for rows created by the fake database. */
export function nextId(): string {
  idCounter += 1;
  return `f0000000-0000-4000-8000-${idCounter.toString(16).padStart(12, '0')}`;
}
const GEN_ID: Default = nextId;

export const TABLE_COLUMNS: Record<string, Record<string, Default | null>> = {
  administrator_profiles: {
    id: GEN_ID,
    user_id: null,
    created_at: () => NOW,
  },
  assistance_requests: {
    id: GEN_ID,
    beneficiary_id: null,
    request_date: () => NOW,
    request_type: null,
    description: null,
    status: () => 'pending',
    priority: () => 'normal',
    preferred_collection_area: null,
    admin_notes: null,
    reviewed_by: null,
    reviewed_at: null,
  },
  beneficiary_profiles: {
    id: GEN_ID,
    user_id: null,
    residential_address: null,
    assistance_type: null,
    created_at: () => NOW,
    avatar_url: null,
    eligibility_status: null,
  },
  campaign_applications: {
    id: GEN_ID,
    volunteer_id: null,
    campaign_id: null,
    application_date: () => NOW,
    status: () => 'pending',
    participation_role: null,
  },
  campaigns: {
    id: GEN_ID,
    admin_id: null,
    title: null,
    description: null,
    location: null,
    start_date: null,
    end_date: null,
    status: () => 'draft',
    created_at: () => NOW,
    updated_at: () => NOW,
    category: null,
    image_url: null,
    funding_goal: null,
    amount_raised: () => 0,
    is_public: () => true,
  },
  collection_schedules: {
    id: GEN_ID,
    request_id: null,
    programme_name: null,
    location: null,
    collection_date: null,
    collection_time: null,
    status: () => 'upcoming',
    created_at: () => NOW,
  },
  contact_messages: {
    id: GEN_ID,
    first_name: null,
    last_name: null,
    email: null,
    subject: null,
    message: null,
    status: () => 'unread',
    created_at: () => NOW,
  },
  donation_proofs: {
    id: GEN_ID,
    donation_id: null,
    file_path: null,
    file_name: null,
    payment_reference: null,
    payment_date: null,
    admin_comment: null,
    verification_status: () => 'pending',
    reviewed_by: null,
    reviewed_at: null,
    uploaded_at: () => NOW,
  },
  donations: {
    id: GEN_ID,
    donor_id: null,
    campaign_id: null,
    amount: null,
    donation_date: () => NOW,
    payment_method: null,
    status: () => 'pending',
    receipt_number: null,
    donation_kind: () => 'money',
    item_description: null,
    item_quantity: null,
    payment_reference: null,
    notes: null,
  },
  donor_profiles: {
    id: GEN_ID,
    user_id: null,
    donation_preference: null,
    created_at: () => NOW,
    avatar_url: null,
    member_since: null,
  },
  events: {
    id: GEN_ID,
    admin_id: null,
    campaign_id: null,
    title: null,
    description: null,
    location: null,
    event_date: null,
    status: () => 'draft',
    created_at: () => NOW,
    updated_at: () => NOW,
  },
  notifications: {
    id: GEN_ID,
    user_id: null,
    message: null,
    notification_date: () => NOW,
    notification_type: null,
    status: () => 'unread',
    title: null,
    link_url: null,
    related_entity_type: null,
    related_entity_id: null,
  },
  profiles: {
    id: null,
    role: () => 'beneficiary',
    full_name: null,
    email: null,
    phone_number: null,
    created_at: () => NOW,
    updated_at: () => NOW,
    account_status: () => 'pending',
    invited_by: null,
    invited_at: null,
    avatar_url: null,
    avatar_change_count: () => 0,
  },
  reports: {
    id: GEN_ID,
    admin_id: null,
    report_name: null,
    generated_at: () => NOW,
    report_type: null,
    status: () => 'generated',
    metadata: () => '{}',
    file_path: null,
  },
  sponsor_profiles: {
    id: GEN_ID,
    user_id: null,
    organisation_name: null,
    sponsorship_type: null,
    created_at: () => NOW,
    representative_name: null,
    business_address: null,
    sponsor_level: null,
    logo_url: null,
  },
  sponsorship_request_responses: {
    id: GEN_ID,
    request_id: null,
    sponsor_id: null,
    sponsorship_id: null,
    status: () => 'interested',
    notes: null,
    responded_at: () => NOW,
  },
  sponsorship_requests: {
    id: GEN_ID,
    campaign_id: null,
    title: null,
    requested_support: null,
    category: null,
    priority: () => 'normal',
    deadline: null,
    estimated_impact: null,
    status: () => 'open',
    created_by: null,
    created_at: () => NOW,
  },
  sponsorships: {
    id: GEN_ID,
    sponsor_id: null,
    campaign_id: null,
    amount: null,
    sponsorship_date: () => NOW,
    sponsorship_type: null,
    status: () => 'pending',
  },
  supporting_documents: {
    id: GEN_ID,
    request_id: null,
    document_name: null,
    document_type: null,
    file_path: null,
    upload_date: () => NOW,
    verification_status: () => 'pending',
  },
  user_settings: {
    user_id: null,
    theme_preference: () => 'system',
    notify_campaign_updates: () => true,
    notify_request_updates: () => true,
    notify_donation_updates: () => true,
    created_at: () => NOW,
    updated_at: () => NOW,
  },
  volunteer_assignments: {
    id: GEN_ID,
    application_id: null,
    volunteer_id: null,
    campaign_id: null,
    role: null,
    location: null,
    schedule: null,
    start_date: null,
    end_date: null,
    status: () => 'upcoming',
    created_at: () => NOW,
  },
  volunteer_hours: {
    id: GEN_ID,
    assignment_id: null,
    volunteer_id: null,
    hours: null,
    work_date: null,
    notes: null,
    recorded_at: () => NOW,
  },
  volunteer_profiles: {
    id: GEN_ID,
    user_id: null,
    residential_address: null,
    availability_status: () => 'available',
    created_at: () => NOW,
    preferred_area: null,
    member_since: null,
    status: () => 'active',
    avatar_url: null,
  },
};

/** NOT NULL columns per table (a missing value without a default fails with 23502). */
export const NOT_NULL: Record<string, string[]> = {
  administrator_profiles: ['id', 'user_id', 'created_at'],
  assistance_requests: ['id', 'beneficiary_id', 'request_date', 'request_type', 'description', 'status'],
  beneficiary_profiles: ['id', 'user_id', 'created_at'],
  campaign_applications: ['id', 'volunteer_id', 'campaign_id', 'application_date', 'status'],
  campaigns: ['id', 'admin_id', 'title', 'description', 'location', 'start_date', 'status', 'created_at', 'updated_at', 'amount_raised', 'is_public'],
  collection_schedules: ['id', 'location', 'collection_date', 'status', 'created_at'],
  contact_messages: ['id', 'first_name', 'last_name', 'email', 'subject', 'message', 'status', 'created_at'],
  donation_proofs: ['id', 'donation_id', 'file_path', 'verification_status', 'uploaded_at'],
  donations: ['id', 'donor_id', 'donation_date', 'payment_method', 'status', 'donation_kind'],
  donor_profiles: ['id', 'user_id', 'created_at'],
  events: ['id', 'admin_id', 'title', 'location', 'event_date', 'status', 'created_at', 'updated_at'],
  notifications: ['id', 'user_id', 'message', 'notification_date', 'notification_type', 'status'],
  profiles: ['id', 'role', 'full_name', 'email', 'created_at', 'updated_at', 'account_status', 'avatar_change_count'],
  reports: ['id', 'admin_id', 'report_name', 'generated_at', 'report_type', 'status', 'metadata'],
  sponsor_profiles: ['id', 'user_id', 'organisation_name', 'created_at'],
  sponsorship_request_responses: ['id', 'request_id', 'sponsor_id', 'status', 'responded_at'],
  sponsorship_requests: ['id', 'title', 'requested_support', 'status', 'created_at'],
  sponsorships: ['id', 'sponsor_id', 'amount', 'sponsorship_date', 'status'],
  supporting_documents: ['id', 'request_id', 'document_name', 'file_path', 'upload_date', 'verification_status'],
  user_settings: ['user_id', 'theme_preference', 'notify_campaign_updates', 'notify_request_updates', 'notify_donation_updates', 'created_at', 'updated_at'],
  volunteer_assignments: ['id', 'volunteer_id', 'campaign_id', 'role', 'status', 'created_at'],
  volunteer_hours: ['id', 'volunteer_id', 'hours', 'work_date', 'recorded_at'],
  volunteer_profiles: ['id', 'user_id', 'created_at'],
};
