-- TMF Community Support System - M2 "Database ready" seed (01 auth users)
-- Generated by /workspace/tmf/seed/gen/build.py. All seed ids match the LIKE pattern
--   '5eed____-5eed-4eed-8eed-5eed5eed5eed'  and all seed auth emails match 'seed.%@example.com'.
-- Run order: 01_seed_auth_users.sql -> 02_seed.sql -> 03_seed_verify.sql ; cleanup: 04_seed_cleanup.sql
--
-- Creates 42 confirmed email/password test accounts directly in auth.users + auth.identities
-- (columns as Supabase Auth expects them: token columns '' not NULL, bcrypt hash, provider 'email').
-- 14 login accounts (2 administrators + 3 per other role) get the test password; the other 28
-- are data-only (encrypted_password = '') and cannot sign in with a password.
-- Side effects (existing triggers, by design):
--   on_auth_user_created -> handle_new_user(): profiles row (account_status 'pending', role from
--     metadata; 'administrator' is downgraded to 'beneficiary') + the matching role profile;
--   create_user_settings_after_profile_insert -> user_settings row with defaults.
--   02_seed.sql then activates the accounts and promotes the 2 administrators.
-- PASSWORD: replace __SET_TEST_PASSWORD_HERE__ below in the SQL Editor ONLY, run, then close the tab
-- without saving. Never commit a real value. If the placeholder is left in, the script aborts.
-- Idempotent: re-running skips seed users that already exist (on conflict do nothing).
begin;

create temporary table _seed_users (id uuid primary key, identity_id uuid not null, email text not null unique,
  meta jsonb not null, can_login boolean not null) on commit drop;
insert into _seed_users (id, identity_id, email, meta, can_login) values
  ('5eed0101-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1301-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.admin.thandi.mokoena@example.com', '{"full_name": "Thandi Mokoena", "role": "administrator", "phone_number": "+27 71 555 0101", "email_verified": true}'::jsonb, true),
  ('5eed0102-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1302-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.admin.pieter.vandermerwe@example.com', '{"full_name": "Pieter van der Merwe", "role": "administrator", "phone_number": "+27 82 555 0102", "email_verified": true}'::jsonb, true),
  ('5eed0103-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1303-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.donor.sipho.ndlovu@example.com', '{"full_name": "Sipho Ndlovu", "role": "donor", "phone_number": "+27 72 555 0201", "email_verified": true}'::jsonb, true),
  ('5eed0104-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1304-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.donor.ayesha.patel@example.com', '{"full_name": "Ayesha Patel", "role": "donor", "phone_number": "+27 83 555 0202", "email_verified": true}'::jsonb, true),
  ('5eed0105-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1305-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.donor.johan.botha@example.com', '{"full_name": "Johan Botha", "role": "donor", "phone_number": "+27 82 555 0203", "email_verified": true}'::jsonb, true),
  ('5eed0106-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1306-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.donor.lerato.khumalo@example.com', '{"full_name": "Lerato Khumalo", "role": "donor", "phone_number": "+27 73 555 0204", "email_verified": true}'::jsonb, false),
  ('5eed0107-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1307-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.donor.nomvula.dlamini@example.com', '{"full_name": "Nomvula Dlamini", "role": "donor", "phone_number": "+27 76 555 0205", "email_verified": true}'::jsonb, false),
  ('5eed0108-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1308-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.donor.ruan.steyn@example.com', '{"full_name": "Ruan Steyn", "role": "donor", "phone_number": "+27 84 555 0206", "email_verified": true}'::jsonb, false),
  ('5eed0109-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1309-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.donor.fatima.adams@example.com', '{"full_name": "Fatima Adams", "role": "donor", "phone_number": "+27 61 555 0207", "email_verified": true}'::jsonb, false),
  ('5eed010a-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed130a-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.donor.kagiso.molefe@example.com', '{"full_name": "Kagiso Molefe", "role": "donor", "phone_number": "+27 79 555 0208", "email_verified": true}'::jsonb, false),
  ('5eed010b-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed130b-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.donor.zanele.mthembu@example.com', '{"full_name": "Zanele Mthembu", "role": "donor", "phone_number": "+27 71 555 0209", "email_verified": true}'::jsonb, false),
  ('5eed010c-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed130c-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.donor.david.naidoo@example.com', '{"full_name": "David Naidoo", "role": "donor", "phone_number": "+27 83 555 0210", "email_verified": true}'::jsonb, false),
  ('5eed010d-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed130d-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.beneficiary.nosipho.zulu@example.com', '{"full_name": "Nosipho Zulu", "role": "beneficiary", "phone_number": "+27 72 555 0301", "email_verified": true}'::jsonb, true),
  ('5eed010e-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed130e-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.beneficiary.bongani.mahlangu@example.com', '{"full_name": "Bongani Mahlangu", "role": "beneficiary", "phone_number": "+27 73 555 0302", "email_verified": true}'::jsonb, true),
  ('5eed010f-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed130f-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.beneficiary.precious.sithole@example.com', '{"full_name": "Precious Sithole", "role": "beneficiary", "phone_number": "+27 76 555 0303", "email_verified": true}'::jsonb, true),
  ('5eed0110-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1310-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.beneficiary.mpho.maseko@example.com', '{"full_name": "Mpho Maseko", "role": "beneficiary", "phone_number": "+27 78 555 0304", "email_verified": true}'::jsonb, false),
  ('5eed0111-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1311-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.beneficiary.lindiwe.nkosi@example.com', '{"full_name": "Lindiwe Nkosi", "role": "beneficiary", "phone_number": "+27 79 555 0305", "email_verified": true}'::jsonb, false),
  ('5eed0112-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1312-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.beneficiary.themba.shabalala@example.com', '{"full_name": "Themba Shabalala", "role": "beneficiary", "phone_number": "+27 81 555 0306", "email_verified": true}'::jsonb, false),
  ('5eed0113-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1313-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.beneficiary.dineo.phiri@example.com', '{"full_name": "Dineo Phiri", "role": "beneficiary", "phone_number": "+27 82 555 0307", "email_verified": true}'::jsonb, false),
  ('5eed0114-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1314-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.beneficiary.andile.cele@example.com', '{"full_name": "Andile Cele", "role": "beneficiary", "phone_number": "+27 83 555 0308", "email_verified": true}'::jsonb, false),
  ('5eed0115-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1315-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.beneficiary.rethabile.mofokeng@example.com', '{"full_name": "Rethabile Mofokeng", "role": "beneficiary", "phone_number": "+27 84 555 0309", "email_verified": true}'::jsonb, false),
  ('5eed0116-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1316-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.beneficiary.busisiwe.ntuli@example.com', '{"full_name": "Busisiwe Ntuli", "role": "beneficiary", "phone_number": "+27 60 555 0310", "email_verified": true}'::jsonb, false),
  ('5eed0117-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1317-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.volunteer.kabelo.tau@example.com', '{"full_name": "Kabelo Tau", "role": "volunteer", "phone_number": "+27 71 555 0401", "email_verified": true}'::jsonb, true),
  ('5eed0118-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1318-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.volunteer.amahle.ngcobo@example.com', '{"full_name": "Amahle Ngcobo", "role": "volunteer", "phone_number": "+27 72 555 0402", "email_verified": true}'::jsonb, true),
  ('5eed0119-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1319-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.volunteer.liam.jacobs@example.com', '{"full_name": "Liam Jacobs", "role": "volunteer", "phone_number": "+27 73 555 0403", "email_verified": true}'::jsonb, true),
  ('5eed011a-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed131a-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.volunteer.naledi.radebe@example.com', '{"full_name": "Naledi Radebe", "role": "volunteer", "phone_number": "+27 74 555 0404", "email_verified": true}'::jsonb, false),
  ('5eed011b-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed131b-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.volunteer.tshepo.mabaso@example.com', '{"full_name": "Tshepo Mabaso", "role": "volunteer", "phone_number": "+27 76 555 0405", "email_verified": true}'::jsonb, false),
  ('5eed011c-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed131c-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.volunteer.chantel.fourie@example.com', '{"full_name": "Chantel Fourie", "role": "volunteer", "phone_number": "+27 82 555 0406", "email_verified": true}'::jsonb, false),
  ('5eed011d-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed131d-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.volunteer.sibusiso.hlongwane@example.com', '{"full_name": "Sibusiso Hlongwane", "role": "volunteer", "phone_number": "+27 83 555 0407", "email_verified": true}'::jsonb, false),
  ('5eed011e-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed131e-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.volunteer.refilwe.moagi@example.com', '{"full_name": "Refilwe Moagi", "role": "volunteer", "phone_number": "+27 84 555 0408", "email_verified": true}'::jsonb, false),
  ('5eed011f-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed131f-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.volunteer.yusuf.ebrahim@example.com', '{"full_name": "Yusuf Ebrahim", "role": "volunteer", "phone_number": "+27 61 555 0409", "email_verified": true}'::jsonb, false),
  ('5eed0120-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1320-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.volunteer.palesa.motaung@example.com', '{"full_name": "Palesa Motaung", "role": "volunteer", "phone_number": "+27 79 555 0410", "email_verified": true}'::jsonb, false),
  ('5eed0121-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1321-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.sponsor.ubuntu.fresh@example.com', '{"full_name": "Neo Seabi", "role": "sponsor", "phone_number": "+27 11 555 0501", "email_verified": true, "organisation_name": "Ubuntu Fresh Foods (Pty) Ltd"}'::jsonb, true),
  ('5eed0122-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1322-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.sponsor.jozi.build@example.com', '{"full_name": "Marius Pretorius", "role": "sponsor", "phone_number": "+27 11 555 0502", "email_verified": true, "organisation_name": "Jozi Build Supply Co"}'::jsonb, true),
  ('5eed0123-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1323-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.sponsor.kasi.connect@example.com', '{"full_name": "Lungile Mkhize", "role": "sponsor", "phone_number": "+27 12 555 0503", "email_verified": true, "organisation_name": "Kasi Connect Telecoms"}'::jsonb, true),
  ('5eed0124-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1324-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.sponsor.highveld.pharmacies@example.com', '{"full_name": "Priya Govender", "role": "sponsor", "phone_number": "+27 11 555 0504", "email_verified": true, "organisation_name": "Highveld Community Pharmacies"}'::jsonb, false),
  ('5eed0125-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1325-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.sponsor.sunrise.stationers@example.com', '{"full_name": "Karabo Lekota", "role": "sponsor", "phone_number": "+27 11 555 0505", "email_verified": true, "organisation_name": "Sunrise Stationers"}'::jsonb, false),
  ('5eed0126-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1326-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.sponsor.mzansi.transport@example.com', '{"full_name": "Vusi Nkuna", "role": "sponsor", "phone_number": "+27 11 555 0506", "email_verified": true, "organisation_name": "Mzansi Transport Logistics"}'::jsonb, false),
  ('5eed0127-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1327-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.sponsor.protea.foundation@example.com', '{"full_name": "Elaine Smit", "role": "sponsor", "phone_number": "+27 21 555 0507", "email_verified": true, "organisation_name": "Protea Community Bank Foundation"}'::jsonb, false),
  ('5eed0128-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1328-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.sponsor.siyakhula.bakery@example.com', '{"full_name": "Nandi Mbatha", "role": "sponsor", "phone_number": "+27 11 555 0508", "email_verified": true, "organisation_name": "Siyakhula Bakery"}'::jsonb, false),
  ('5eed0129-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed1329-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.sponsor.karoo.solar@example.com', '{"full_name": "Hendrik Visser", "role": "sponsor", "phone_number": "+27 53 555 0509", "email_verified": true, "organisation_name": "Karoo Solar Energy"}'::jsonb, false),
  ('5eed012a-5eed-4eed-8eed-5eed5eed5eed'::uuid, '5eed132a-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'seed.sponsor.golden.grain@example.com', '{"full_name": "Tumelo Sebola", "role": "sponsor", "phone_number": "+27 18 555 0510", "email_verified": true, "organisation_name": "Golden Grain Millers"}'::jsonb, false);

-- Guards: the auth columns this script writes exist; no seed email/id belongs to another account.
do $$
declare v_missing text;
begin
  select string_agg(c, ', ') into v_missing
  from unnest(array['instance_id','id','aud','role','email','encrypted_password','email_confirmed_at',
                    'confirmation_token','recovery_token','email_change_token_new','email_change',
                    'email_change_token_current','phone_change','phone_change_token','reauthentication_token',
                    'raw_app_meta_data','raw_user_meta_data','is_super_admin','created_at','updated_at',
                    'is_sso_user','is_anonymous']) c
  where not exists (select 1 from information_schema.columns
                    where table_schema = 'auth' and table_name = 'users' and column_name = c);
  if v_missing is not null then raise exception 'auth.users is missing expected columns: %', v_missing; end if;
  select string_agg(c, ', ') into v_missing
  from unnest(array['id','provider_id','user_id','identity_data','provider','last_sign_in_at','created_at','updated_at']) c
  where not exists (select 1 from information_schema.columns
                    where table_schema = 'auth' and table_name = 'identities' and column_name = c);
  if v_missing is not null then raise exception 'auth.identities is missing expected columns: %', v_missing; end if;
  if exists (select 1 from auth.users u join _seed_users s on lower(u.email) = lower(s.email) and u.id <> s.id)
     or exists (select 1 from auth.users u join _seed_users s on u.id = s.id and lower(u.email) <> lower(s.email))
     or exists (select 1 from public.profiles p join _seed_users s on lower(p.email) = lower(s.email) and p.id <> s.id) then
    raise exception 'A seed email or id is already used by a different account - aborting, nothing written.';
  end if;
end $$;

-- The only statement that contains the password: a plain INSERT (pg_stat_statements stores it
-- parameterised). Each login account gets its own bcrypt salt (cost 10, as Supabase Auth uses).
with pw(v) as (select '__SET_TEST_PASSWORD_HERE__'::text)
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token,
  raw_app_meta_data, raw_user_meta_data, is_super_admin, created_at, updated_at,
  is_sso_user, is_anonymous)
select '00000000-0000-0000-0000-000000000000'::uuid, s.id, 'authenticated', 'authenticated', s.email,
       case when s.can_login then extensions.crypt(pw.v, extensions.gen_salt('bf', 10)) else '' end,
       now(), '', '', '', '', '', '', '', '',
       '{"provider": "email", "providers": ["email"]}'::jsonb, s.meta, false, now(), now(), false, false
from _seed_users s cross join pw
order by s.id
on conflict (id) do nothing;

insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
select s.identity_id, s.id::text, s.id,
       jsonb_build_object('sub', s.id::text, 'email', s.email, 'email_verified', true, 'phone_verified', false),
       'email', null, now(), now()
from _seed_users s
order by s.id
on conflict (provider_id, provider) do nothing;

-- Post-checks (an exception rolls everything back): placeholder replaced, triggers provisioned.
do $$
declare v_bad text;
begin
  if exists (select 1 from auth.users u join _seed_users s on s.id = u.id
             where case when u.encrypted_password like '$2%' -- bcrypt hashes only ('' would be an invalid salt)
                        then u.encrypted_password = extensions.crypt('__SET_TEST_PASSWORD_HERE__', u.encrypted_password) else false end) then
    raise exception 'The test password placeholder was not replaced - aborting, nothing written.';
  end if;
  select string_agg(s.email, ', ') into v_bad from _seed_users s
  where not exists (select 1 from auth.identities i where i.user_id = s.id and i.provider = 'email')
     or not exists (select 1 from public.profiles p where p.id = s.id)
     or not exists (select 1 from public.user_settings us where us.user_id = s.id);
  if v_bad is not null then raise exception 'Provisioning incomplete for: %', v_bad; end if;
  raise notice 'seed auth users present: % (login-enabled: %)',
    (select count(*) from auth.users u join _seed_users s on s.id = u.id),
    (select count(*) from auth.users u join _seed_users s on s.id = u.id where u.encrypted_password <> '');
end $$;

commit;
