-- TMF Community Support System - M2 "Database ready" seed (02 seed data)
-- Generated by /workspace/tmf/seed/gen/build.py. All seed ids match the LIKE pattern
--   '5eed____-5eed-4eed-8eed-5eed5eed5eed'  and all seed auth emails match 'seed.%@example.com'.
-- Run order: 01_seed_auth_users.sql -> 02_seed.sql -> 03_seed_verify.sql ; cleanup: 04_seed_cleanup.sql
--
-- Requires 01_seed_auth_users.sql (42 seed accounts + their trigger-provisioned profiles).
-- Runs as postgres (SQL Editor) in ONE transaction. RLS does not apply to the table owner and the
-- protect_* triggers let non-API roles through, so admin-type values are seeded directly.
-- Idempotent: fixed ids + "on conflict (id) do nothing"; the updates set fixed values.
-- Trigger effects: refresh_campaign_amount recomputes campaigns.amount_raised from successful money
-- donations (amount_raised is never written here); contact_messages_notify_admins adds one
-- notification per administrator for each NEW contact message (non-seed administrators too);
-- the *_status_notification triggers fire on UPDATE only, so rows inserted with a final status do
-- NOT notify anyone - a realistic notification history is inserted explicitly instead.
begin;

do $$
declare v_auth int; v_prof int;
begin
  select count(*) into v_auth from auth.users where id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' and email like 'seed.%@example.com';
  select count(*) into v_prof from public.profiles where id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed';
  if v_auth <> 42 or v_prof <> 42 then
    raise exception 'Expected 42 seed auth users and profiles, found % / %. Run 01_seed_auth_users.sql first.', v_auth, v_prof;
  end if;
end $$;

-- 1. profiles: activate, promote the two administrators, invitation trail
update public.profiles p set account_status = v.status, phone_number = v.phone
from (values
  ('5eed0101-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 71 555 0101'),
  ('5eed0102-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 82 555 0102'),
  ('5eed0103-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 72 555 0201'),
  ('5eed0104-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 83 555 0202'),
  ('5eed0105-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 82 555 0203'),
  ('5eed0106-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 73 555 0204'),
  ('5eed0107-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 76 555 0205'),
  ('5eed0108-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 84 555 0206'),
  ('5eed0109-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 61 555 0207'),
  ('5eed010a-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 79 555 0208'),
  ('5eed010b-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 71 555 0209'),
  ('5eed010c-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 83 555 0210'),
  ('5eed010d-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 72 555 0301'),
  ('5eed010e-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 73 555 0302'),
  ('5eed010f-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 76 555 0303'),
  ('5eed0110-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 78 555 0304'),
  ('5eed0111-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 79 555 0305'),
  ('5eed0112-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 81 555 0306'),
  ('5eed0113-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 82 555 0307'),
  ('5eed0114-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 83 555 0308'),
  ('5eed0115-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 84 555 0309'),
  ('5eed0116-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'pending', '+27 60 555 0310'),
  ('5eed0117-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 71 555 0401'),
  ('5eed0118-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 72 555 0402'),
  ('5eed0119-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 73 555 0403'),
  ('5eed011a-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 74 555 0404'),
  ('5eed011b-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 76 555 0405'),
  ('5eed011c-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 82 555 0406'),
  ('5eed011d-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 83 555 0407'),
  ('5eed011e-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 84 555 0408'),
  ('5eed011f-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 61 555 0409'),
  ('5eed0120-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'suspended', '+27 79 555 0410'),
  ('5eed0121-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 11 555 0501'),
  ('5eed0122-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 11 555 0502'),
  ('5eed0123-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 12 555 0503'),
  ('5eed0124-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 11 555 0504'),
  ('5eed0125-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 11 555 0505'),
  ('5eed0126-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 11 555 0506'),
  ('5eed0127-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 21 555 0507'),
  ('5eed0128-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 11 555 0508'),
  ('5eed0129-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 53 555 0509'),
  ('5eed012a-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'active', '+27 18 555 0510')
) v(id, status, phone)
where p.id = v.id;
update public.profiles set role = 'administrator' where id in ('5eed0101-5eed-4eed-8eed-5eed5eed5eed', '5eed0102-5eed-4eed-8eed-5eed5eed5eed');
update public.profiles set invited_by = '5eed0101-5eed-4eed-8eed-5eed5eed5eed', invited_at = '2026-01-12 09:00:00+02' where id = '5eed0102-5eed-4eed-8eed-5eed5eed5eed';
insert into public.administrator_profiles (id, user_id) values
  ('5eed0201-5eed-4eed-8eed-5eed5eed5eed', '5eed0101-5eed-4eed-8eed-5eed5eed5eed'),
  ('5eed0202-5eed-4eed-8eed-5eed5eed5eed', '5eed0102-5eed-4eed-8eed-5eed5eed5eed')
on conflict (id) do nothing;
-- handle_new_user downgraded the two admin sign-ups to beneficiary and gave them a beneficiary profile:
delete from public.beneficiary_profiles where user_id in ('5eed0101-5eed-4eed-8eed-5eed5eed5eed', '5eed0102-5eed-4eed-8eed-5eed5eed5eed');

-- 2. role profiles (rows created by handle_new_user; admin-type fields are set here as postgres)
update public.donor_profiles d set donation_preference = v.pref, member_since = v.since::date
from (values
  ('5eed0103-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Monthly EFT', '2025-11-03'),
  ('5eed0104-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Disaster relief appeals', '2026-01-15'),
  ('5eed0105-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Education campaigns', '2026-02-20'),
  ('5eed0106-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Health and dignity drives', '2026-03-08'),
  ('5eed0107-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Food security', '2026-03-30'),
  ('5eed0108-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'In-kind goods', '2026-04-12'),
  ('5eed0109-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Once-off EFT', '2026-05-05'),
  ('5eed010a-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'School supplies (in-kind)', '2026-05-21'),
  ('5eed010b-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Monthly EFT', '2026-06-16'),
  ('5eed010c-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Food security', '2026-08-01')
) v(user_id, pref, since)
where d.user_id = v.user_id;
update public.beneficiary_profiles b set residential_address = v.addr, assistance_type = v.atype, eligibility_status = v.elig
from (values
  ('5eed010d-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Erf 1432, 7th Avenue, Alexandra, 2090', 'Food parcel', 'eligible'),
  ('5eed010e-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Section 4, Tembisa, 1632', 'School supplies', 'eligible'),
  ('5eed010f-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Extension 2, Diepsloot, 2189', 'Food parcel', 'pending_review'),
  ('5eed0110-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Zone 5, Meadowlands, Soweto, 1852', 'Clothing', 'eligible'),
  ('5eed0111-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Extension 7, Orange Farm, 1841', 'Medical support', 'not_eligible'),
  ('5eed0112-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'U Section, Umlazi, Durban, 4031', 'Other', 'eligible'),
  ('5eed0113-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Ivory Park Ext 2, Midrand, 1689', 'Food parcel', 'pending_review'),
  ('5eed0114-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Kliptown, Soweto, 1811', 'School supplies', 'pending_review'),
  ('5eed0115-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Block L, Soshanguve, 0152', 'Medical support', 'pending_review'),
  ('5eed0116-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Mamelodi East, Pretoria, 0122', 'Food parcel', null)
) v(user_id, addr, atype, elig)
where b.user_id = v.user_id;
update public.volunteer_profiles vp set residential_address = v.addr, availability_status = v.avail,
  preferred_area = v.area, member_since = v.since::date, status = v.status
from (values
  ('5eed0117-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Wynberg, Sandton, 2090', 'available', 'Alexandra', '2026-02-01', 'active'),
  ('5eed0118-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Birch Acres, Kempton Park, 1618', 'available', 'Tembisa', '2026-03-14', 'active'),
  ('5eed0119-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Silverton, Pretoria, 0184', 'busy', 'Mamelodi', '2026-04-02', 'active'),
  ('5eed011a-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Soshanguve South, 0152', 'available', 'Soshanguve', '2026-05-10', 'active'),
  ('5eed011b-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Pimville, Soweto, 1809', 'available', 'Soweto', '2026-05-01', 'active'),
  ('5eed011c-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Glen Marais, Kempton Park, 1619', 'unavailable', 'Tembisa', '2026-06-20', 'active'),
  ('5eed011d-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Eldorado Park Ext 4, 1811', 'available', 'Eldorado Park', '2026-05-28', 'active'),
  ('5eed011e-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Cosmo City, Randburg, 2188', 'busy', 'Diepsloot', '2026-07-15', 'active'),
  ('5eed011f-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Overport, Durban, 4091', 'available', 'eThekwini', '2026-04-10', 'active'),
  ('5eed0120-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Orlando East, Soweto, 1804', 'unavailable', 'Soweto', '2026-08-09', 'inactive')
) v(user_id, addr, avail, area, since, status)
where vp.user_id = v.user_id;
update public.sponsor_profiles sp set organisation_name = v.org, representative_name = v.rep, business_address = v.addr,
  sponsorship_type = v.stype, sponsor_level = v.lvl
from (values
  ('5eed0121-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Ubuntu Fresh Foods (Pty) Ltd', 'Neo Seabi', '14 Commerce Road, Midrand, 1685', 'in_kind', 'gold'),
  ('5eed0122-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Jozi Build Supply Co', 'Marius Pretorius', '88 Main Reef Road, Denver, Johannesburg, 2094', 'in_kind', 'gold'),
  ('5eed0123-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Kasi Connect Telecoms', 'Lungile Mkhize', 'Menlyn Corporate Park, Pretoria, 0181', 'financial', 'silver'),
  ('5eed0124-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Highveld Community Pharmacies', 'Priya Govender', '22 Voortrekker Road, Benoni, 1501', 'in_kind', 'silver'),
  ('5eed0125-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Sunrise Stationers', 'Karabo Lekota', '5 Olifantsfontein Road, Tembisa, 1632', 'in_kind', 'bronze'),
  ('5eed0126-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Mzansi Transport Logistics', 'Vusi Nkuna', 'Germiston Industrial Park, 1401', 'services', 'bronze'),
  ('5eed0127-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Protea Community Bank Foundation', 'Elaine Smit', '1 Thibault Square, Cape Town, 8001', 'financial', 'gold'),
  ('5eed0128-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Siyakhula Bakery', 'Nandi Mbatha', 'Shop 3, Alexandra Plaza, 2090', 'in_kind', 'bronze'),
  ('5eed0129-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Karoo Solar Energy', 'Hendrik Visser', '12 Market Street, Kimberley, 8301', 'financial', 'silver'),
  ('5eed012a-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'Golden Grain Millers', 'Tumelo Sebola', 'Industrial Site, Klerksdorp, 2571', 'financial', null)
) v(user_id, org, rep, addr, stype, lvl)
where sp.user_id = v.user_id;

-- 3. user_settings (rows created by create_default_user_settings; vary some preferences)
update public.user_settings us set theme_preference = v.theme, notify_campaign_updates = v.c,
  notify_request_updates = v.r, notify_donation_updates = v.d
from (values
  ('5eed0101-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'dark', true, true, true),
  ('5eed0102-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'light', true, true, true),
  ('5eed0103-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'dark', false, true, true),
  ('5eed0105-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'light', true, true, false),
  ('5eed010d-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'light', true, true, true),
  ('5eed010f-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'dark', false, true, false),
  ('5eed0117-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'dark', true, false, true),
  ('5eed011a-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'light', false, false, false),
  ('5eed0121-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'light', true, false, true),
  ('5eed0125-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'dark', true, true, true),
  ('5eed0128-5eed-4eed-8eed-5eed5eed5eed'::uuid, 'system', false, true, true)
) v(user_id, theme, c, r, d)
where us.user_id = v.user_id;

-- 4. campaigns (amount_raised stays 0 here: refresh_campaign_amount maintains it)
insert into public.campaigns (id, admin_id, title, description, location, start_date, end_date, status, category, funding_goal, is_public, created_at, updated_at) values
  ('5eed0301-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', 'Winter Blanket Drive 2026', 'Blankets, beanies and warm winter packs for families and elderly residents of Soweto.', 'Soweto, Johannesburg', '2026-05-01', '2026-08-31', 'closed', 'Winter Relief', 50000, true, '2026-05-01 08:00:00+02', now()),
  ('5eed0302-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', 'Back-to-School Stationery Campaign', 'Stationery packs and school shoes for learners at no-fee primary schools in Tembisa.', 'Tembisa, Ekurhuleni', '2026-10-01', '2027-01-31', 'active', 'Education', 30000, true, '2026-10-01 08:00:00+02', now()),
  ('5eed0303-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', 'Alexandra Food Parcel Programme', 'Monthly food parcels for child-headed and pensioner households in Alexandra.', 'Alexandra, Johannesburg', '2026-03-01', '2027-02-28', 'active', 'Food Security', 80000, true, '2026-03-01 08:00:00+02', now()),
  ('5eed0304-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', 'Diepsloot Community Food Garden', 'Seedlings, tools and water tanks for a community food garden run by local volunteers.', 'Diepsloot, Johannesburg', '2026-08-01', '2026-12-15', 'active', 'Food Security', 25000, true, '2026-08-01 08:00:00+02', now()),
  ('5eed0305-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', 'Mandela Day Care Packs', '67 minutes of service: hygiene and care packs for residents of an Orange Farm old-age home.', 'Orange Farm, Johannesburg', '2026-07-01', '2026-07-31', 'closed', 'Community', 15000, true, '2026-07-01 08:00:00+02', now()),
  ('5eed0306-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', 'Youth Skills and CV Workshops', 'Free CV writing, interview preparation and digital skills workshops for unemployed youth.', 'Mamelodi, Pretoria', '2026-09-01', '2026-11-30', 'active', 'Skills Development', 20000, true, '2026-09-01 08:00:00+02', now()),
  ('5eed0307-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', 'Sanitary Dignity Drive', 'Reusable sanitary kits so that girls in Soshanguve do not miss school days.', 'Soshanguve, Pretoria', '2026-08-15', '2026-11-15', 'active', 'Health', 18000, true, '2026-08-15 08:00:00+02', now()),
  ('5eed0308-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', 'KZN Flood Relief Appeal', 'Emergency food, water, blankets and building materials for flood-affected families in eThekwini.', 'eThekwini, KwaZulu-Natal', '2026-04-15', '2026-06-30', 'closed', 'Disaster Relief', 100000, true, '2026-04-15 08:00:00+02', now()),
  ('5eed0309-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', 'Early Childhood Toy Library', 'A rotating toy and book library shared by three early childhood development centres.', 'Ivory Park, Midrand', '2026-11-01', '2027-03-31', 'draft', 'Education', 10000, false, now(), now()),
  ('5eed030a-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', 'Heritage Day Community Feast', 'A shared meal and cultural celebration for families supported by TMF.', 'Kliptown, Soweto', '2026-09-24', '2026-09-24', 'cancelled', 'Community', 8000, true, '2026-09-24 08:00:00+02', now()),
  ('5eed030b-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', 'Matric Exam Support Bootcamp', 'Weekend maths and physical science revision classes before the matric final exams.', 'Tembisa, Ekurhuleni', '2026-09-05', '2026-11-28', 'active', 'Education', 22000, true, '2026-09-05 08:00:00+02', now()),
  ('5eed030c-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', 'Elderly Home Visits Programme', 'Volunteers visit housebound pensioners with groceries and collect chronic medication.', 'Eldorado Park, Johannesburg', '2026-06-01', '2026-12-31', 'active', 'Health', 12000, false, '2026-06-01 08:00:00+02', now())
on conflict (id) do nothing;

-- 5. events
insert into public.events (id, admin_id, campaign_id, title, description, location, event_date, status) values
  ('5eed0401-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 'Food parcel packing day', 'Volunteers pack October parcels.', 'Alexandra Community Hall, 3rd Avenue', '2026-10-17 09:00:00+02', 'scheduled'),
  ('5eed0402-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 'October parcel distribution', 'Collection day for registered households.', 'Alexandra Community Hall, 3rd Avenue', '2026-10-24 08:00:00+02', 'scheduled'),
  ('5eed0403-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '5eed0302-5eed-4eed-8eed-5eed5eed5eed', 'Stationery pack assembly', 'Sorting donated stationery into Grade R-7 packs.', 'Tembisa Civic Centre', '2026-11-14 10:00:00+02', 'scheduled'),
  ('5eed0404-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '5eed030b-5eed-4eed-8eed-5eed5eed5eed', 'Matric maths revision Saturday', 'Past-paper revision with volunteer tutors.', 'Tembisa Public Library', '2026-10-10 09:00:00+02', 'scheduled'),
  ('5eed0405-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '5eed0304-5eed-4eed-8eed-5eed5eed5eed', 'Garden planting day', 'Planting spinach, cabbage and tomato seedlings.', 'Diepsloot Ext 2 community plot', '2026-09-19 08:30:00+02', 'completed'),
  ('5eed0406-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '5eed0301-5eed-4eed-8eed-5eed5eed5eed', 'Winter blanket handover', 'Blanket packs handed to registered families.', 'Meadowlands Community Centre, Soweto', '2026-07-18 10:00:00+02', 'completed'),
  ('5eed0407-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '5eed0305-5eed-4eed-8eed-5eed5eed5eed', 'Mandela Day at the old-age home', 'Care packs and 67 minutes of service.', 'Orange Farm Old Age Home', '2026-07-18 09:00:00+02', 'completed'),
  ('5eed0408-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '5eed030a-5eed-4eed-8eed-5eed5eed5eed', 'Heritage Day feast', 'Cancelled because of a venue double-booking.', 'Kliptown Open Air Museum grounds', '2026-09-24 12:00:00+02', 'cancelled'),
  ('5eed0409-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '5eed0306-5eed-4eed-8eed-5eed5eed5eed', 'CV clinic', 'One-on-one CV reviews and mock interviews.', 'Mamelodi Youth Centre', '2026-10-21 17:00:00+02', 'scheduled'),
  ('5eed040a-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', null, 'Volunteer induction evening', 'Safeguarding, POPIA and safety briefing for new volunteers.', 'TMF office, Braamfontein', '2026-11-05 18:00:00+02', 'draft')
on conflict (id) do nothing;

-- 6. sponsorship requests
insert into public.sponsorship_requests (id, campaign_id, title, requested_support, category, priority, deadline, estimated_impact, status, created_by) values
  ('5eed0501-5eed-4eed-8eed-5eed5eed5eed', '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 'Monthly maize meal and cooking oil', '400 x 10 kg maize meal and 400 x 2 L cooking oil per month', 'Food', 'high', '2026-10-31', '400 households fed for a month', 'open', '5eed0201-5eed-4eed-8eed-5eed5eed5eed'),
  ('5eed0502-5eed-4eed-8eed-5eed5eed5eed', '5eed0302-5eed-4eed-8eed-5eed5eed5eed', 'School shoes for Grade R-7 learners', '250 pairs of black school shoes, sizes 10 to 6', 'Education', 'normal', '2026-12-15', '250 learners start the year in proper shoes', 'open', '5eed0202-5eed-4eed-8eed-5eed5eed5eed'),
  ('5eed0503-5eed-4eed-8eed-5eed5eed5eed', '5eed0304-5eed-4eed-8eed-5eed5eed5eed', 'Water tanks and drip irrigation', 'Two 5000 L water tanks and a drip irrigation kit', 'Infrastructure', 'normal', '2026-11-15', 'Garden produce for about 60 families', 'accepted', '5eed0201-5eed-4eed-8eed-5eed5eed5eed'),
  ('5eed0504-5eed-4eed-8eed-5eed5eed5eed', '5eed0307-5eed-4eed-8eed-5eed5eed5eed', 'Reusable sanitary kits', '300 reusable sanitary kits with carry bags', 'Health', 'urgent', '2026-10-20', '300 girls no longer miss school each month', 'open', '5eed0201-5eed-4eed-8eed-5eed5eed5eed'),
  ('5eed0505-5eed-4eed-8eed-5eed5eed5eed', '5eed0306-5eed-4eed-8eed-5eed5eed5eed', 'Laptops for the CV workshops', '10 refurbished laptops with office software', 'Technology', 'normal', '2026-10-31', 'About 120 young people trained per quarter', 'accepted', '5eed0202-5eed-4eed-8eed-5eed5eed5eed'),
  ('5eed0506-5eed-4eed-8eed-5eed5eed5eed', '5eed0308-5eed-4eed-8eed-5eed5eed5eed', 'Building materials for flood-damaged homes', 'Roof sheeting, cement and timber for 20 homes', 'Disaster Relief', 'urgent', '2026-06-15', '20 families back under a safe roof', 'closed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed'),
  ('5eed0507-5eed-4eed-8eed-5eed5eed5eed', '5eed030b-5eed-4eed-8eed-5eed5eed5eed', 'Calculators and revision guides', '150 scientific calculators and maths/science study guides', 'Education', 'high', '2026-10-15', '150 matric learners better prepared', 'accepted', '5eed0202-5eed-4eed-8eed-5eed5eed5eed'),
  ('5eed0508-5eed-4eed-8eed-5eed5eed5eed', '5eed030c-5eed-4eed-8eed-5eed5eed5eed', 'Transport for home visits', 'Monthly fuel vouchers and a minibus with driver on Thursdays', 'Transport', 'low', '2026-12-01', '80 pensioners visited every week', 'open', '5eed0201-5eed-4eed-8eed-5eed5eed5eed'),
  ('5eed0509-5eed-4eed-8eed-5eed5eed5eed', '5eed030a-5eed-4eed-8eed-5eed5eed5eed', 'Catering for the Heritage Day feast', 'Meat, pap, salads and drinks for 300 people', 'Food', 'normal', '2026-09-20', '300 guests served', 'declined', '5eed0202-5eed-4eed-8eed-5eed5eed5eed'),
  ('5eed050a-5eed-4eed-8eed-5eed5eed5eed', '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 'Bread for parcel days', '200 loaves of bread per distribution day', 'Food', 'normal', '2026-11-30', '200 households receive fresh bread', 'open', '5eed0201-5eed-4eed-8eed-5eed5eed5eed')
on conflict (id) do nothing;

-- 7. sponsorships
insert into public.sponsorships (id, sponsor_id, campaign_id, amount, sponsorship_date, sponsorship_type, status) values
  ('5eed0601-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0121-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 25000, '2026-04-10 10:00:00+02', 'in_kind', 'successful'),
  ('5eed0602-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0122-5eed-4eed-8eed-5eed5eed5eed'), '5eed0308-5eed-4eed-8eed-5eed5eed5eed', 40000, '2026-05-02 11:30:00+02', 'in_kind', 'successful'),
  ('5eed0603-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0123-5eed-4eed-8eed-5eed5eed5eed'), '5eed0306-5eed-4eed-8eed-5eed5eed5eed', 15000, '2026-09-05 09:15:00+02', 'financial', 'successful'),
  ('5eed0604-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0124-5eed-4eed-8eed-5eed5eed5eed'), '5eed0307-5eed-4eed-8eed-5eed5eed5eed', 9000, '2026-08-20 14:00:00+02', 'in_kind', 'successful'),
  ('5eed0605-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0125-5eed-4eed-8eed-5eed5eed5eed'), '5eed0302-5eed-4eed-8eed-5eed5eed5eed', 12000, '2026-10-02 08:45:00+02', 'in_kind', 'pending'),
  ('5eed0606-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0126-5eed-4eed-8eed-5eed5eed5eed'), '5eed030c-5eed-4eed-8eed-5eed5eed5eed', 6000, '2026-06-15 12:00:00+02', 'services', 'successful'),
  ('5eed0607-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0127-5eed-4eed-8eed-5eed5eed5eed'), '5eed030b-5eed-4eed-8eed-5eed5eed5eed', 20000, '2026-09-10 10:30:00+02', 'financial', 'successful'),
  ('5eed0608-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0128-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 4800, '2026-10-05 07:30:00+02', 'in_kind', 'pending'),
  ('5eed0609-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0129-5eed-4eed-8eed-5eed5eed5eed'), '5eed0304-5eed-4eed-8eed-5eed5eed5eed', 18000, '2026-08-25 13:00:00+02', 'financial', 'successful'),
  ('5eed060a-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed012a-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 30000, '2026-07-01 09:00:00+02', 'financial', 'failed'),
  ('5eed060b-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0127-5eed-4eed-8eed-5eed5eed5eed'), '5eed0308-5eed-4eed-8eed-5eed5eed5eed', 50000, '2026-04-20 15:00:00+02', 'financial', 'successful'),
  ('5eed060c-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0121-5eed-4eed-8eed-5eed5eed5eed'), '5eed030a-5eed-4eed-8eed-5eed5eed5eed', 7500, '2026-09-01 10:00:00+02', 'in_kind', 'cancelled')
on conflict (id) do nothing;

-- 8. sponsorship request responses
insert into public.sponsorship_request_responses (id, request_id, sponsor_id, sponsorship_id, status, notes, responded_at) values
  ('5eed0701-5eed-4eed-8eed-5eed5eed5eed', '5eed0501-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0121-5eed-4eed-8eed-5eed5eed5eed'), '5eed0601-5eed-4eed-8eed-5eed5eed5eed', 'accepted', 'Monthly delivery from our Midrand distribution centre.', '2026-04-08 09:00:00+02'),
  ('5eed0702-5eed-4eed-8eed-5eed5eed5eed', '5eed0501-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed012a-5eed-4eed-8eed-5eed5eed5eed'), null, 'interested', 'Can supply maize meal at cost; awaiting board approval.', '2026-10-02 10:00:00+02'),
  ('5eed0703-5eed-4eed-8eed-5eed5eed5eed', '5eed0503-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0129-5eed-4eed-8eed-5eed5eed5eed'), '5eed0609-5eed-4eed-8eed-5eed5eed5eed', 'accepted', 'Tanks and installation sponsored.', '2026-08-22 11:00:00+02'),
  ('5eed0704-5eed-4eed-8eed-5eed5eed5eed', '5eed0505-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0123-5eed-4eed-8eed-5eed5eed5eed'), '5eed0603-5eed-4eed-8eed-5eed5eed5eed', 'accepted', 'Ten refurbished laptops reserved.', '2026-09-03 14:00:00+02'),
  ('5eed0705-5eed-4eed-8eed-5eed5eed5eed', '5eed0507-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0127-5eed-4eed-8eed-5eed5eed5eed'), '5eed0607-5eed-4eed-8eed-5eed5eed5eed', 'accepted', 'Funding approved by the foundation committee.', '2026-09-08 16:00:00+02'),
  ('5eed0706-5eed-4eed-8eed-5eed5eed5eed', '5eed0504-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0124-5eed-4eed-8eed-5eed5eed5eed'), null, 'interested', 'Checking stock levels with our supplier.', '2026-09-28 09:30:00+02'),
  ('5eed0707-5eed-4eed-8eed-5eed5eed5eed', '5eed0502-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0125-5eed-4eed-8eed-5eed5eed5eed'), '5eed0605-5eed-4eed-8eed-5eed5eed5eed', 'interested', 'Quote for 250 pairs sent to TMF.', '2026-10-01 12:00:00+02'),
  ('5eed0708-5eed-4eed-8eed-5eed5eed5eed', '5eed0506-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0122-5eed-4eed-8eed-5eed5eed5eed'), '5eed0602-5eed-4eed-8eed-5eed5eed5eed', 'accepted', 'Materials delivered to Umlazi in two loads.', '2026-04-30 08:00:00+02'),
  ('5eed0709-5eed-4eed-8eed-5eed5eed5eed', '5eed0508-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0126-5eed-4eed-8eed-5eed5eed5eed'), '5eed0606-5eed-4eed-8eed-5eed5eed5eed', 'accepted', 'Minibus and driver every Thursday until December.', '2026-06-10 10:00:00+02'),
  ('5eed070a-5eed-4eed-8eed-5eed5eed5eed', '5eed0509-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0128-5eed-4eed-8eed-5eed5eed5eed'), null, 'declined', 'Bakery closed on the public holiday.', '2026-09-12 15:00:00+02'),
  ('5eed070b-5eed-4eed-8eed-5eed5eed5eed', '5eed050a-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0128-5eed-4eed-8eed-5eed5eed5eed'), '5eed0608-5eed-4eed-8eed-5eed5eed5eed', 'interested', 'Can bake 200 loaves on the last Saturday of each month.', '2026-10-04 07:00:00+02'),
  ('5eed070c-5eed-4eed-8eed-5eed5eed5eed', '5eed0502-5eed-4eed-8eed-5eed5eed5eed', (select id from public.sponsor_profiles where user_id = '5eed0123-5eed-4eed-8eed-5eed5eed5eed'), null, 'declined', 'Outside our CSI focus area this year.', '2026-10-06 11:00:00+02')
on conflict (id) do nothing;

-- 9. donations (AFTER INSERT trigger refresh_campaign_amount updates campaigns.amount_raised)
insert into public.donations (id, donor_id, campaign_id, donation_kind, amount, donation_date, payment_method, status, receipt_number, item_description, item_quantity, payment_reference, notes) values
  ('5eed0801-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0103-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 'money', 1500, '2026-03-15 10:12:00+02', 'EFT', 'successful', 'TMF-SEED-R0001', null, null, 'SN-ALEX-0315', null),
  ('5eed0802-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0103-5eed-4eed-8eed-5eed5eed5eed'), '5eed0301-5eed-4eed-8eed-5eed5eed5eed', 'money', 750, '2026-05-20 19:40:00+02', 'EFT', 'successful', 'TMF-SEED-R0002', null, null, 'SN-WINTER-0520', null),
  ('5eed0803-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0104-5eed-4eed-8eed-5eed5eed5eed'), '5eed0308-5eed-4eed-8eed-5eed5eed5eed', 'money', 5000, '2026-04-22 08:05:00+02', 'EFT', 'successful', 'TMF-SEED-R0003', null, null, 'AP-KZN-0422', 'In memory of my grandmother.'),
  ('5eed0804-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0104-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 'money', 2500, '2026-09-30 12:30:00+02', 'EFT', 'pending', null, null, null, 'AP-ALEX-0930', null),
  ('5eed0805-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0105-5eed-4eed-8eed-5eed5eed5eed'), '5eed0302-5eed-4eed-8eed-5eed5eed5eed', 'money', 1000, '2026-10-03 21:15:00+02', 'Card', 'successful', 'TMF-SEED-R0004', null, null, null, null),
  ('5eed0806-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0105-5eed-4eed-8eed-5eed5eed5eed'), '5eed030b-5eed-4eed-8eed-5eed5eed5eed', 'money', 3000, '2026-09-12 09:00:00+02', 'EFT', 'successful', 'TMF-SEED-R0005', null, null, 'JB-MATRIC-0912', null),
  ('5eed0807-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0106-5eed-4eed-8eed-5eed5eed5eed'), '5eed0307-5eed-4eed-8eed-5eed5eed5eed', 'money', 450, '2026-08-28 13:20:00+02', 'EFT', 'failed', null, null, null, 'LK-SDD-0828', null),
  ('5eed0808-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0106-5eed-4eed-8eed-5eed5eed5eed'), '5eed0307-5eed-4eed-8eed-5eed5eed5eed', 'money', 500, '2026-09-02 13:25:00+02', 'EFT', 'successful', 'TMF-SEED-R0006', null, null, 'LK-SDD-0902', 'Corrected amount after failed transfer.'),
  ('5eed0809-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0107-5eed-4eed-8eed-5eed5eed5eed'), '5eed0304-5eed-4eed-8eed-5eed5eed5eed', 'money', 2000, '2026-08-10 17:45:00+02', 'EFT', 'successful', 'TMF-SEED-R0007', null, null, 'ND-GARDEN-0810', null),
  ('5eed080a-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0107-5eed-4eed-8eed-5eed5eed5eed'), null, 'money', 1200, '2026-06-16 10:00:00+02', 'EFT', 'successful', 'TMF-SEED-R0008', null, null, 'ND-GEN-0616', 'Youth Day general donation.'),
  ('5eed080b-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0108-5eed-4eed-8eed-5eed5eed5eed'), '5eed0301-5eed-4eed-8eed-5eed5eed5eed', 'in_kind', null, '2026-06-05 11:00:00+02', 'Drop-off', 'successful', 'TMF-SEED-R0009', 'Double blankets', 40, null, 'Dropped off at the Braamfontein office.'),
  ('5eed080c-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0108-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 'in_kind', null, '2026-10-01 15:30:00+02', 'Drop-off', 'pending', null, 'Tinned food (assorted)', 120, null, null),
  ('5eed080d-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0109-5eed-4eed-8eed-5eed5eed5eed'), '5eed0306-5eed-4eed-8eed-5eed5eed5eed', 'money', 800, '2026-09-18 20:10:00+02', 'EFT', 'pending', null, null, null, 'FA-CV-0918', null),
  ('5eed080e-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed0109-5eed-4eed-8eed-5eed5eed5eed'), '5eed030c-5eed-4eed-8eed-5eed5eed5eed', 'money', 350, '2026-07-10 08:30:00+02', 'EFT', 'cancelled', null, null, null, 'FA-ELD-0710', 'Duplicate transfer, cancelled by donor.'),
  ('5eed080f-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed010a-5eed-4eed-8eed-5eed5eed5eed'), '5eed0302-5eed-4eed-8eed-5eed5eed5eed', 'in_kind', null, '2026-10-04 09:00:00+02', 'Drop-off', 'pending', null, 'Grade 4 stationery packs', 60, null, null),
  ('5eed0810-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed010a-5eed-4eed-8eed-5eed5eed5eed'), '5eed0308-5eed-4eed-8eed-5eed5eed5eed', 'money', 10000, '2026-05-01 09:30:00+02', 'EFT', 'successful', 'TMF-SEED-R0010', null, null, 'KM-KZN-0501', null),
  ('5eed0811-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed010b-5eed-4eed-8eed-5eed5eed5eed'), '5eed030b-5eed-4eed-8eed-5eed5eed5eed', 'money', 600, '2026-09-25 18:00:00+02', 'EFT', 'successful', 'TMF-SEED-R0011', null, null, 'ZM-MATRIC-0925', null),
  ('5eed0812-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed010b-5eed-4eed-8eed-5eed5eed5eed'), '5eed0305-5eed-4eed-8eed-5eed5eed5eed', 'in_kind', null, '2026-07-12 10:00:00+02', 'Drop-off', 'successful', 'TMF-SEED-R0012', 'Toiletry care packs', 67, null, 'For Mandela Day.'),
  ('5eed0813-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed010c-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 'money', 250, '2026-10-06 07:50:00+02', 'EFT', 'pending', null, null, null, 'DN-ALEX-1006', null),
  ('5eed0814-5eed-4eed-8eed-5eed5eed5eed', (select id from public.donor_profiles where user_id = '5eed010c-5eed-4eed-8eed-5eed5eed5eed'), '5eed0307-5eed-4eed-8eed-5eed5eed5eed', 'money', 1800, '2026-09-08 16:40:00+02', 'EFT', 'failed', null, null, null, 'DN-SDD-0908', null)
on conflict (id) do nothing;

-- 10. donation proofs (files are NOT uploaded to Storage; paths follow <user_id>/<file>)
insert into public.donation_proofs (id, donation_id, file_path, file_name, payment_reference, payment_date, admin_comment, verification_status, reviewed_by, reviewed_at, uploaded_at) values
  ('5eed0901-5eed-4eed-8eed-5eed5eed5eed', '5eed0801-5eed-4eed-8eed-5eed5eed5eed', '5eed0103-5eed-4eed-8eed-5eed5eed5eed/seed-proof-01.pdf', 'proof-of-payment-01.pdf', 'SN-ALEX-0315', '2026-03-15', 'Verified against bank statement. Thank you!', 'approved', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '2026-03-15 15:00:00+02', '2026-03-15 10:12:00+02'),
  ('5eed0902-5eed-4eed-8eed-5eed5eed5eed', '5eed0802-5eed-4eed-8eed-5eed5eed5eed', '5eed0103-5eed-4eed-8eed-5eed5eed5eed/seed-proof-02.pdf', 'proof-of-payment-02.pdf', 'SN-WINTER-0520', '2026-05-20', 'Verified.', 'approved', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '2026-05-20 15:00:00+02', '2026-05-20 19:40:00+02'),
  ('5eed0903-5eed-4eed-8eed-5eed5eed5eed', '5eed0803-5eed-4eed-8eed-5eed5eed5eed', '5eed0104-5eed-4eed-8eed-5eed5eed5eed/seed-proof-03.pdf', 'proof-of-payment-03.pdf', 'AP-KZN-0422', '2026-04-22', 'Verified and allocated to the flood relief appeal.', 'approved', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '2026-04-22 15:00:00+02', '2026-04-22 08:05:00+02'),
  ('5eed0904-5eed-4eed-8eed-5eed5eed5eed', '5eed0804-5eed-4eed-8eed-5eed5eed5eed', '5eed0104-5eed-4eed-8eed-5eed5eed5eed/seed-proof-04.pdf', 'proof-of-payment-04.pdf', 'AP-ALEX-0930', '2026-09-30', null, 'pending', null, null, '2026-09-30 12:30:00+02'),
  ('5eed0905-5eed-4eed-8eed-5eed5eed5eed', '5eed0806-5eed-4eed-8eed-5eed5eed5eed', '5eed0105-5eed-4eed-8eed-5eed5eed5eed/seed-proof-06.pdf', 'proof-of-payment-06.pdf', 'JB-MATRIC-0912', '2026-09-12', 'Verified.', 'approved', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '2026-09-12 15:00:00+02', '2026-09-12 09:00:00+02'),
  ('5eed0906-5eed-4eed-8eed-5eed5eed5eed', '5eed0807-5eed-4eed-8eed-5eed5eed5eed', '5eed0106-5eed-4eed-8eed-5eed5eed5eed/seed-proof-07.pdf', 'proof-of-payment-07.pdf', 'LK-SDD-0828', '2026-08-28', 'Amount on the proof does not match the pledge. Please resubmit.', 'rejected', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '2026-08-28 15:00:00+02', '2026-08-28 13:20:00+02'),
  ('5eed0907-5eed-4eed-8eed-5eed5eed5eed', '5eed0808-5eed-4eed-8eed-5eed5eed5eed', '5eed0106-5eed-4eed-8eed-5eed5eed5eed/seed-proof-08.pdf', 'proof-of-payment-08.pdf', 'LK-SDD-0902', '2026-09-02', 'Verified.', 'approved', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '2026-09-02 15:00:00+02', '2026-09-02 13:25:00+02'),
  ('5eed0908-5eed-4eed-8eed-5eed5eed5eed', '5eed0809-5eed-4eed-8eed-5eed5eed5eed', '5eed0107-5eed-4eed-8eed-5eed5eed5eed/seed-proof-09.pdf', 'proof-of-payment-09.pdf', 'ND-GARDEN-0810', '2026-08-10', 'Verified - seedlings ordered.', 'approved', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '2026-08-10 15:00:00+02', '2026-08-10 17:45:00+02'),
  ('5eed0909-5eed-4eed-8eed-5eed5eed5eed', '5eed080d-5eed-4eed-8eed-5eed5eed5eed', '5eed0109-5eed-4eed-8eed-5eed5eed5eed/seed-proof-13.pdf', 'proof-of-payment-13.pdf', 'FA-CV-0918', '2026-09-18', null, 'pending', null, null, '2026-09-18 20:10:00+02'),
  ('5eed090a-5eed-4eed-8eed-5eed5eed5eed', '5eed0810-5eed-4eed-8eed-5eed5eed5eed', '5eed010a-5eed-4eed-8eed-5eed5eed5eed/seed-proof-16.pdf', 'proof-of-payment-16.pdf', 'KM-KZN-0501', '2026-05-01', 'Verified.', 'approved', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '2026-05-01 15:00:00+02', '2026-05-01 09:30:00+02'),
  ('5eed090b-5eed-4eed-8eed-5eed5eed5eed', '5eed0813-5eed-4eed-8eed-5eed5eed5eed', '5eed010c-5eed-4eed-8eed-5eed5eed5eed/seed-proof-19.pdf', 'proof-of-payment-19.pdf', 'DN-ALEX-1006', '2026-10-06', null, 'pending', null, null, '2026-10-06 07:50:00+02'),
  ('5eed090c-5eed-4eed-8eed-5eed5eed5eed', '5eed0814-5eed-4eed-8eed-5eed5eed5eed', '5eed010c-5eed-4eed-8eed-5eed5eed5eed/seed-proof-20.pdf', 'proof-of-payment-20.pdf', 'DN-SDD-0908', '2026-09-08', 'Payment was reversed by the bank.', 'rejected', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '2026-09-08 15:00:00+02', '2026-09-08 16:40:00+02')
on conflict (id) do nothing;

-- 11. assistance requests
insert into public.assistance_requests (id, beneficiary_id, request_date, request_type, description, status, priority, preferred_collection_area, admin_notes, reviewed_by, reviewed_at) values
  ('5eed0a01-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed010d-5eed-4eed-8eed-5eed5eed5eed'), '2026-09-02 10:15:00+02', 'Food parcel', 'Single mother of three; lost part-time work in August and needs food support.', 'approved', 'high', 'Alexandra', 'Eligible. Added to the October distribution list.', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '2026-09-02 10:15:00+02'::timestamptz + interval '2 days'),
  ('5eed0a02-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed010d-5eed-4eed-8eed-5eed5eed5eed'), '2026-01-20 09:00:00+02', 'School supplies', 'Stationery and uniform for two children starting Grade 1 and Grade 4.', 'completed', 'normal', 'Alexandra', 'Packs collected on 7 February.', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '2026-01-20 09:00:00+02'::timestamptz + interval '2 days'),
  ('5eed0a03-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed010e-5eed-4eed-8eed-5eed5eed5eed'), '2026-10-01 14:00:00+02', 'School supplies', 'Grandmother caring for three learners needs stationery for 2027.', 'approved', 'normal', 'Tembisa', 'Approved for the November pack day.', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '2026-10-01 14:00:00+02'::timestamptz + interval '2 days'),
  ('5eed0a04-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed010f-5eed-4eed-8eed-5eed5eed5eed'), '2026-10-05 08:30:00+02', 'Food parcel', 'Household of six with no income since the factory closed.', 'under_review', 'urgent', 'Diepsloot', 'Home visit booked; awaiting SASSA letter.', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '2026-10-05 08:30:00+02'::timestamptz + interval '2 days'),
  ('5eed0a05-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed0110-5eed-4eed-8eed-5eed5eed5eed'), '2026-06-10 11:45:00+02', 'Clothing', 'Winter clothing for two children aged 5 and 9.', 'completed', 'normal', 'Soweto', 'Included in the winter blanket handover.', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '2026-06-10 11:45:00+02'::timestamptz + interval '2 days'),
  ('5eed0a06-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed0111-5eed-4eed-8eed-5eed5eed5eed'), '2026-08-14 13:10:00+02', 'Medical support', 'Needs transport to Chris Hani Baragwanath for monthly check-ups.', 'rejected', 'low', 'Orange Farm', 'Referred to the clinic''s patient transport service; outside TMF scope.', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '2026-08-14 13:10:00+02'::timestamptz + interval '2 days'),
  ('5eed0a07-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed0112-5eed-4eed-8eed-5eed5eed5eed'), '2026-05-03 09:20:00+02', 'Other', 'Shack roof and belongings damaged in the floods.', 'approved', 'urgent', 'Umlazi', 'Approved for materials from the flood appeal.', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '2026-05-03 09:20:00+02'::timestamptz + interval '2 days'),
  ('5eed0a08-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed0113-5eed-4eed-8eed-5eed5eed5eed'), '2026-10-06 16:00:00+02', 'Food parcel', 'Unemployed couple with a newborn baby.', 'pending', 'normal', 'Ivory Park', null, null, null),
  ('5eed0a09-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed0114-5eed-4eed-8eed-5eed5eed5eed'), '2026-10-07 10:40:00+02', 'School supplies', 'Matric learner needs a scientific calculator and study guides.', 'pending', 'high', 'Kliptown', null, null, null),
  ('5eed0a0a-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed0115-5eed-4eed-8eed-5eed5eed5eed'), '2026-09-29 12:00:00+02', 'Medical support', 'Chronic medication collection; cannot travel to the clinic.', 'under_review', 'normal', 'Soshanguve', 'Checking whether the home visits programme can cover this.', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', '2026-09-29 12:00:00+02'::timestamptz + interval '2 days'),
  ('5eed0a0b-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed0116-5eed-4eed-8eed-5eed5eed5eed'), '2026-10-07 18:20:00+02', 'Food parcel', 'Pensioner looking after two grandchildren.', 'pending', 'normal', 'Mamelodi', null, null, null),
  ('5eed0a0c-5eed-4eed-8eed-5eed5eed5eed', (select id from public.beneficiary_profiles where user_id = '5eed010e-5eed-4eed-8eed-5eed5eed5eed'), '2026-08-25 09:00:00+02', 'Food parcel', 'Temporary food support while waiting for a SASSA grant.', 'completed', 'normal', 'Tembisa', 'Three monthly parcels provided.', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', '2026-08-25 09:00:00+02'::timestamptz + interval '2 days')
on conflict (id) do nothing;

-- 12. supporting documents (files are NOT uploaded to Storage)
insert into public.supporting_documents (id, request_id, document_name, document_type, file_path, upload_date, verification_status) values
  ('5eed0b01-5eed-4eed-8eed-5eed5eed5eed', '5eed0a01-5eed-4eed-8eed-5eed5eed5eed', 'ID copy', 'application/pdf', '5eed010d-5eed-4eed-8eed-5eed5eed5eed/seed-01-id-copy.pdf', '2026-09-02 10:15:00+02', 'approved'),
  ('5eed0b02-5eed-4eed-8eed-5eed5eed5eed', '5eed0a01-5eed-4eed-8eed-5eed5eed5eed', 'UIF letter', 'application/pdf', '5eed010d-5eed-4eed-8eed-5eed5eed5eed/seed-02-uif-letter.pdf', '2026-09-02 10:15:00+02', 'approved'),
  ('5eed0b03-5eed-4eed-8eed-5eed5eed5eed', '5eed0a02-5eed-4eed-8eed-5eed5eed5eed', 'School acceptance letter', 'image/jpeg', '5eed010d-5eed-4eed-8eed-5eed5eed5eed/seed-03-school-letter.jpg', '2026-01-20 09:00:00+02', 'approved'),
  ('5eed0b04-5eed-4eed-8eed-5eed5eed5eed', '5eed0a03-5eed-4eed-8eed-5eed5eed5eed', 'Proof of residence', 'application/pdf', '5eed010e-5eed-4eed-8eed-5eed5eed5eed/seed-04-proof-of-residence.pdf', '2026-10-01 14:00:00+02', 'approved'),
  ('5eed0b05-5eed-4eed-8eed-5eed5eed5eed', '5eed0a04-5eed-4eed-8eed-5eed5eed5eed', 'SASSA application receipt', 'image/jpeg', '5eed010f-5eed-4eed-8eed-5eed5eed5eed/seed-05-sassa-receipt.jpg', '2026-10-05 08:30:00+02', 'pending'),
  ('5eed0b06-5eed-4eed-8eed-5eed5eed5eed', '5eed0a05-5eed-4eed-8eed-5eed5eed5eed', 'Birth certificates', 'application/pdf', '5eed0110-5eed-4eed-8eed-5eed5eed5eed/seed-06-birth-certificates.pdf', '2026-06-10 11:45:00+02', 'approved'),
  ('5eed0b07-5eed-4eed-8eed-5eed5eed5eed', '5eed0a06-5eed-4eed-8eed-5eed5eed5eed', 'Clinic card', 'image/png', '5eed0111-5eed-4eed-8eed-5eed5eed5eed/seed-07-clinic-card.png', '2026-08-14 13:10:00+02', 'rejected'),
  ('5eed0b08-5eed-4eed-8eed-5eed5eed5eed', '5eed0a07-5eed-4eed-8eed-5eed5eed5eed', 'Ward councillor letter', 'application/pdf', '5eed0112-5eed-4eed-8eed-5eed5eed5eed/seed-08-councillor-letter.pdf', '2026-05-03 09:20:00+02', 'approved'),
  ('5eed0b09-5eed-4eed-8eed-5eed5eed5eed', '5eed0a08-5eed-4eed-8eed-5eed5eed5eed', 'ID copy', 'image/jpeg', '5eed0113-5eed-4eed-8eed-5eed5eed5eed/seed-09-id-copy.jpg', '2026-10-06 16:00:00+02', 'pending'),
  ('5eed0b0a-5eed-4eed-8eed-5eed5eed5eed', '5eed0a09-5eed-4eed-8eed-5eed5eed5eed', 'School report', 'application/pdf', '5eed0114-5eed-4eed-8eed-5eed5eed5eed/seed-10-school-report.pdf', '2026-10-07 10:40:00+02', 'pending'),
  ('5eed0b0b-5eed-4eed-8eed-5eed5eed5eed', '5eed0a0a-5eed-4eed-8eed-5eed5eed5eed', 'Prescription', 'image/jpeg', '5eed0115-5eed-4eed-8eed-5eed5eed5eed/seed-11-prescription.jpg', '2026-09-29 12:00:00+02', 'pending'),
  ('5eed0b0c-5eed-4eed-8eed-5eed5eed5eed', '5eed0a0b-5eed-4eed-8eed-5eed5eed5eed', 'Pension grant letter', 'application/pdf', '5eed0116-5eed-4eed-8eed-5eed5eed5eed/seed-12-pension-letter.pdf', '2026-10-07 18:20:00+02', 'pending')
on conflict (id) do nothing;

-- 13. collection schedules
insert into public.collection_schedules (id, request_id, programme_name, location, collection_date, collection_time, status) values
  ('5eed0c01-5eed-4eed-8eed-5eed5eed5eed', '5eed0a01-5eed-4eed-8eed-5eed5eed5eed', 'Alexandra Food Parcel Programme', 'Alexandra Community Hall, 3rd Avenue', '2026-10-24', '08:00-12:00', 'confirmed'),
  ('5eed0c02-5eed-4eed-8eed-5eed5eed5eed', '5eed0a01-5eed-4eed-8eed-5eed5eed5eed', 'Alexandra Food Parcel Programme', 'Alexandra Community Hall, 3rd Avenue', '2026-09-26', '08:00-12:00', 'missed'),
  ('5eed0c03-5eed-4eed-8eed-5eed5eed5eed', '5eed0a02-5eed-4eed-8eed-5eed5eed5eed', 'School supplies support', 'Alexandra Community Hall, 3rd Avenue', '2026-02-07', '09:00-11:00', 'completed'),
  ('5eed0c04-5eed-4eed-8eed-5eed5eed5eed', '5eed0a03-5eed-4eed-8eed-5eed5eed5eed', 'Back-to-School Stationery Campaign', 'Tembisa Civic Centre', '2026-11-14', '10:00-13:00', 'upcoming'),
  ('5eed0c05-5eed-4eed-8eed-5eed5eed5eed', '5eed0a05-5eed-4eed-8eed-5eed5eed5eed', 'Winter Blanket Drive 2026', 'Meadowlands Community Centre, Soweto', '2026-07-18', '10:00-12:00', 'completed'),
  ('5eed0c06-5eed-4eed-8eed-5eed5eed5eed', '5eed0a07-5eed-4eed-8eed-5eed5eed5eed', 'KZN Flood Relief Appeal', 'Umlazi Community Centre', '2026-10-12', '09:00-12:00', 'confirmed'),
  ('5eed0c07-5eed-4eed-8eed-5eed5eed5eed', '5eed0a0c-5eed-4eed-8eed-5eed5eed5eed', 'Alexandra Food Parcel Programme', 'Tembisa Civic Centre', '2026-09-26', '13:00-15:00', 'completed'),
  ('5eed0c08-5eed-4eed-8eed-5eed5eed5eed', null, 'Alexandra Food Parcel Programme', 'Alexandra Community Hall, 3rd Avenue', '2026-11-28', '08:00-12:00', 'upcoming'),
  ('5eed0c09-5eed-4eed-8eed-5eed5eed5eed', null, 'Elderly Home Visits Programme', 'Eldorado Park Clinic parking area', '2026-10-15', '07:30-09:00', 'upcoming'),
  ('5eed0c0a-5eed-4eed-8eed-5eed5eed5eed', null, 'Matric Exam Support Bootcamp', 'Tembisa Public Library', '2026-10-10', '08:30-09:00', 'confirmed')
on conflict (id) do nothing;

-- 14. campaign applications
insert into public.campaign_applications (id, volunteer_id, campaign_id, application_date, status, participation_role) values
  ('5eed0d01-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0117-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', '2026-02-20 10:00:00+02', 'approved', 'Parcel packer'),
  ('5eed0d02-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0117-5eed-4eed-8eed-5eed5eed5eed'), '5eed0304-5eed-4eed-8eed-5eed5eed5eed', '2026-07-28 18:00:00+02', 'approved', 'Garden coordinator'),
  ('5eed0d03-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0118-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', '2026-03-20 12:00:00+02', 'approved', 'Distribution marshal'),
  ('5eed0d04-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0118-5eed-4eed-8eed-5eed5eed5eed'), '5eed030b-5eed-4eed-8eed-5eed5eed5eed', '2026-08-25 19:30:00+02', 'approved', 'Maths tutor'),
  ('5eed0d05-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0119-5eed-4eed-8eed-5eed5eed5eed'), '5eed0306-5eed-4eed-8eed-5eed5eed5eed', '2026-09-02 08:00:00+02', 'approved', 'CV workshop facilitator'),
  ('5eed0d06-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011a-5eed-4eed-8eed-5eed5eed5eed'), '5eed0307-5eed-4eed-8eed-5eed5eed5eed', '2026-08-16 15:00:00+02', 'approved', 'Kit packer'),
  ('5eed0d07-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011b-5eed-4eed-8eed-5eed5eed5eed'), '5eed0302-5eed-4eed-8eed-5eed5eed5eed', '2026-10-03 11:00:00+02', 'pending', 'Stationery packer'),
  ('5eed0d08-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011c-5eed-4eed-8eed-5eed5eed5eed'), '5eed030b-5eed-4eed-8eed-5eed5eed5eed', '2026-08-28 20:00:00+02', 'approved', 'Physical science tutor'),
  ('5eed0d09-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011d-5eed-4eed-8eed-5eed5eed5eed'), '5eed030c-5eed-4eed-8eed-5eed5eed5eed', '2026-05-29 09:00:00+02', 'approved', 'Home visit driver'),
  ('5eed0d0a-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011e-5eed-4eed-8eed-5eed5eed5eed'), '5eed0304-5eed-4eed-8eed-5eed5eed5eed', '2026-08-02 13:00:00+02', 'rejected', 'Garden helper'),
  ('5eed0d0b-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011f-5eed-4eed-8eed-5eed5eed5eed'), '5eed0308-5eed-4eed-8eed-5eed5eed5eed', '2026-04-16 07:00:00+02', 'approved', 'Logistics and warehouse'),
  ('5eed0d0c-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0120-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', '2026-08-12 10:00:00+02', 'rejected', 'Parcel packer'),
  ('5eed0d0d-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0119-5eed-4eed-8eed-5eed5eed5eed'), '5eed0302-5eed-4eed-8eed-5eed5eed5eed', '2026-10-05 17:00:00+02', 'pending', 'Stationery packer'),
  ('5eed0d0e-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011b-5eed-4eed-8eed-5eed5eed5eed'), '5eed0301-5eed-4eed-8eed-5eed5eed5eed', '2026-05-04 09:30:00+02', 'approved', 'Blanket sorter')
on conflict (id) do nothing;

-- 15. volunteer assignments (from approved applications)
insert into public.volunteer_assignments (id, application_id, volunteer_id, campaign_id, role, location, schedule, start_date, end_date, status) values
  ('5eed0e01-5eed-4eed-8eed-5eed5eed5eed', '5eed0d01-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0117-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 'Parcel packer', 'Alexandra Community Hall', 'Saturdays 08:00-12:00', '2026-03-07', null, 'active'),
  ('5eed0e02-5eed-4eed-8eed-5eed5eed5eed', '5eed0d02-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0117-5eed-4eed-8eed-5eed5eed5eed'), '5eed0304-5eed-4eed-8eed-5eed5eed5eed', 'Garden coordinator', 'Diepsloot Ext 2 community plot', 'Wednesday and Saturday mornings', '2026-08-05', '2026-12-15', 'active'),
  ('5eed0e03-5eed-4eed-8eed-5eed5eed5eed', '5eed0d03-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0118-5eed-4eed-8eed-5eed5eed5eed'), '5eed0303-5eed-4eed-8eed-5eed5eed5eed', 'Distribution marshal', 'Alexandra Community Hall', 'Last Saturday of the month', '2026-04-01', null, 'active'),
  ('5eed0e04-5eed-4eed-8eed-5eed5eed5eed', '5eed0d04-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0118-5eed-4eed-8eed-5eed5eed5eed'), '5eed030b-5eed-4eed-8eed-5eed5eed5eed', 'Maths tutor', 'Tembisa Public Library', 'Saturdays 09:00-13:00', '2026-09-05', '2026-11-28', 'active'),
  ('5eed0e05-5eed-4eed-8eed-5eed5eed5eed', '5eed0d05-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0119-5eed-4eed-8eed-5eed5eed5eed'), '5eed0306-5eed-4eed-8eed-5eed5eed5eed', 'CV workshop facilitator', 'Mamelodi Youth Centre', 'Tuesdays 17:00-19:00', '2026-10-21', '2026-11-30', 'upcoming'),
  ('5eed0e06-5eed-4eed-8eed-5eed5eed5eed', '5eed0d06-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011a-5eed-4eed-8eed-5eed5eed5eed'), '5eed0307-5eed-4eed-8eed-5eed5eed5eed', 'Kit packer', 'Soshanguve Block L hall', 'Weekday afternoons', '2026-08-20', '2026-09-30', 'completed'),
  ('5eed0e07-5eed-4eed-8eed-5eed5eed5eed', '5eed0d08-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011c-5eed-4eed-8eed-5eed5eed5eed'), '5eed030b-5eed-4eed-8eed-5eed5eed5eed', 'Physical science tutor', 'Tembisa Public Library', 'Saturdays 09:00-13:00', '2026-09-05', '2026-11-28', 'active'),
  ('5eed0e08-5eed-4eed-8eed-5eed5eed5eed', '5eed0d09-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011d-5eed-4eed-8eed-5eed5eed5eed'), '5eed030c-5eed-4eed-8eed-5eed5eed5eed', 'Home visit driver', 'Eldorado Park', 'Thursdays 08:00-14:00', '2026-06-04', null, 'active'),
  ('5eed0e09-5eed-4eed-8eed-5eed5eed5eed', '5eed0d0b-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011f-5eed-4eed-8eed-5eed5eed5eed'), '5eed0308-5eed-4eed-8eed-5eed5eed5eed', 'Logistics and warehouse', 'Umlazi Community Centre', 'Daily during the appeal', '2026-04-18', '2026-06-30', 'completed'),
  ('5eed0e0a-5eed-4eed-8eed-5eed5eed5eed', '5eed0d0e-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011b-5eed-4eed-8eed-5eed5eed5eed'), '5eed0301-5eed-4eed-8eed-5eed5eed5eed', 'Blanket sorter', 'TMF office, Braamfontein', 'Saturdays', '2026-05-09', '2026-08-31', 'completed')
on conflict (id) do nothing;

-- 16. volunteer hours
insert into public.volunteer_hours (id, assignment_id, volunteer_id, hours, work_date, notes) values
  ('5eed0f01-5eed-4eed-8eed-5eed5eed5eed', '5eed0e01-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0117-5eed-4eed-8eed-5eed5eed5eed'), 4, '2026-09-26', 'Packed 80 parcels.'),
  ('5eed0f02-5eed-4eed-8eed-5eed5eed5eed', '5eed0e01-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0117-5eed-4eed-8eed-5eed5eed5eed'), 4, '2026-10-03', null),
  ('5eed0f03-5eed-4eed-8eed-5eed5eed5eed', '5eed0e02-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0117-5eed-4eed-8eed-5eed5eed5eed'), 3.5, '2026-09-19', 'Planting day.'),
  ('5eed0f04-5eed-4eed-8eed-5eed5eed5eed', '5eed0e03-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0118-5eed-4eed-8eed-5eed5eed5eed'), 5, '2026-09-26', 'Crowd control at distribution.'),
  ('5eed0f05-5eed-4eed-8eed-5eed5eed5eed', '5eed0e04-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0118-5eed-4eed-8eed-5eed5eed5eed'), 4, '2026-09-12', null),
  ('5eed0f06-5eed-4eed-8eed-5eed5eed5eed', '5eed0e04-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed0118-5eed-4eed-8eed-5eed5eed5eed'), 4, '2026-09-19', 'Paper 1 revision.'),
  ('5eed0f07-5eed-4eed-8eed-5eed5eed5eed', '5eed0e06-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011a-5eed-4eed-8eed-5eed5eed5eed'), 6, '2026-09-05', 'Packed 150 kits.'),
  ('5eed0f08-5eed-4eed-8eed-5eed5eed5eed', '5eed0e07-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011c-5eed-4eed-8eed-5eed5eed5eed'), 4, '2026-09-26', null),
  ('5eed0f09-5eed-4eed-8eed-5eed5eed5eed', '5eed0e08-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011d-5eed-4eed-8eed-5eed5eed5eed'), 3, '2026-10-01', 'Visited 12 pensioners.'),
  ('5eed0f0a-5eed-4eed-8eed-5eed5eed5eed', '5eed0e09-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011f-5eed-4eed-8eed-5eed5eed5eed'), 8, '2026-05-02', 'Offloaded two trucks.'),
  ('5eed0f0b-5eed-4eed-8eed-5eed5eed5eed', '5eed0e0a-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011b-5eed-4eed-8eed-5eed5eed5eed'), 5, '2026-07-18', 'Blanket handover.'),
  ('5eed0f0c-5eed-4eed-8eed-5eed5eed5eed', '5eed0e0a-5eed-4eed-8eed-5eed5eed5eed', (select id from public.volunteer_profiles where user_id = '5eed011b-5eed-4eed-8eed-5eed5eed5eed'), 2.5, '2026-06-20', null)
on conflict (id) do nothing;

-- 17. notifications (explicit, realistic history for seed users)
insert into public.notifications (id, user_id, title, message, notification_type, link_url, related_entity_type, related_entity_id, status, notification_date) values
  ('5eed1001-5eed-4eed-8eed-5eed5eed5eed', '5eed0103-5eed-4eed-8eed-5eed5eed5eed', 'Donation Verified', 'Your donation has been successfully verified.', 'donation', '/donor/dashboard/donation-history', 'donation', '5eed0801-5eed-4eed-8eed-5eed5eed5eed', 'read', '2026-03-17 09:00:00+02'),
  ('5eed1002-5eed-4eed-8eed-5eed5eed5eed', '5eed0104-5eed-4eed-8eed-5eed5eed5eed', 'Donation Verified', 'Your donation has been successfully verified.', 'donation', '/donor/dashboard/donation-history', 'donation', '5eed0803-5eed-4eed-8eed-5eed5eed5eed', 'read', '2026-04-23 10:00:00+02'),
  ('5eed1003-5eed-4eed-8eed-5eed5eed5eed', '5eed0106-5eed-4eed-8eed-5eed5eed5eed', 'Donation Requires Attention', 'Your donation could not be verified. Please review your donation information.', 'donation', '/donor/dashboard/donation-history', 'donation', '5eed0807-5eed-4eed-8eed-5eed5eed5eed', 'unread', '2026-08-30 11:00:00+02'),
  ('5eed1004-5eed-4eed-8eed-5eed5eed5eed', '5eed010d-5eed-4eed-8eed-5eed5eed5eed', 'Assistance Request Approved', 'Your assistance request has been approved.', 'assistance', '/dashboard/beneficiary', 'assistance_request', '5eed0a01-5eed-4eed-8eed-5eed5eed5eed', 'unread', '2026-09-04 12:00:00+02'),
  ('5eed1005-5eed-4eed-8eed-5eed5eed5eed', '5eed0110-5eed-4eed-8eed-5eed5eed5eed', 'Assistance Completed', 'Your assistance request has been marked as completed.', 'assistance', '/dashboard/beneficiary', 'assistance_request', '5eed0a05-5eed-4eed-8eed-5eed5eed5eed', 'read', '2026-07-18 13:00:00+02'),
  ('5eed1006-5eed-4eed-8eed-5eed5eed5eed', '5eed0111-5eed-4eed-8eed-5eed5eed5eed', 'Assistance Request Rejected', 'Your assistance request has been rejected.', 'assistance', '/dashboard/beneficiary', 'assistance_request', '5eed0a06-5eed-4eed-8eed-5eed5eed5eed', 'unread', '2026-08-20 09:30:00+02'),
  ('5eed1007-5eed-4eed-8eed-5eed5eed5eed', '5eed0117-5eed-4eed-8eed-5eed5eed5eed', 'Campaign Application Approved', 'Your campaign application has been approved.', 'application', '/volunteer/dashboard', 'campaign_application', '5eed0d01-5eed-4eed-8eed-5eed5eed5eed', 'read', '2026-02-22 08:00:00+02'),
  ('5eed1008-5eed-4eed-8eed-5eed5eed5eed', '5eed011e-5eed-4eed-8eed-5eed5eed5eed', 'Campaign Application Rejected', 'Your campaign application has been rejected.', 'application', '/volunteer/dashboard', 'campaign_application', '5eed0d0a-5eed-4eed-8eed-5eed5eed5eed', 'unread', '2026-08-04 10:00:00+02'),
  ('5eed1009-5eed-4eed-8eed-5eed5eed5eed', '5eed0121-5eed-4eed-8eed-5eed5eed5eed', 'Sponsorship received', 'Thank you - your in-kind sponsorship for the Alexandra Food Parcel Programme has been received.', 'sponsorship', null, 'sponsorship', '5eed0601-5eed-4eed-8eed-5eed5eed5eed', 'read', '2026-04-11 09:00:00+02'),
  ('5eed100a-5eed-4eed-8eed-5eed5eed5eed', '5eed0105-5eed-4eed-8eed-5eed5eed5eed', 'New campaign', 'Back-to-School Stationery Campaign is now open for donations.', 'campaign', null, 'campaign', '5eed0302-5eed-4eed-8eed-5eed5eed5eed', 'unread', '2026-10-01 08:00:00+02'),
  ('5eed100b-5eed-4eed-8eed-5eed5eed5eed', '5eed0118-5eed-4eed-8eed-5eed5eed5eed', 'Reminder: parcel distribution', 'Distribution day is on Saturday 24 October at 08:00.', 'event', null, 'event', '5eed0402-5eed-4eed-8eed-5eed5eed5eed', 'unread', '2026-10-07 17:00:00+02'),
  ('5eed100c-5eed-4eed-8eed-5eed5eed5eed', '5eed0101-5eed-4eed-8eed-5eed5eed5eed', 'New assistance request', 'Precious Sithole submitted an urgent food parcel request.', 'assistance', null, 'assistance_request', '5eed0a04-5eed-4eed-8eed-5eed5eed5eed', 'unread', '2026-10-05 08:31:00+02')
on conflict (id) do nothing;

-- 18. contact messages (AFTER INSERT trigger notifies every administrator, seed and non-seed)
insert into public.contact_messages (id, first_name, last_name, email, subject, message, status, created_at) values
  ('5eed1101-5eed-4eed-8eed-5eed5eed5eed', 'Kgomotso', 'Seleka', 'seed.contact.kgomotso@example.com', 'Volunteering on weekends', 'Hi TMF, I am a teacher in Tembisa and would like to help with matric revision on Saturdays. How do I sign up?', 'read', '2026-09-01 19:20:00+02'),
  ('5eed1102-5eed-4eed-8eed-5eed5eed5eed', 'Michelle', 'Pillay', 'seed.contact.michelle@example.com', 'Company donation of laptops', 'Our company is replacing 25 laptops. Could TMF use them for the youth workshops?', 'read', '2026-09-03 10:05:00+02'),
  ('5eed1103-5eed-4eed-8eed-5eed5eed5eed', 'Sandile', 'Mnisi', 'seed.contact.sandile@example.com', 'Food parcel for my neighbour', 'My elderly neighbour in Alexandra has no food. How can she apply for a parcel?', 'unread', '2026-10-06 07:45:00+02'),
  ('5eed1104-5eed-4eed-8eed-5eed5eed5eed', 'Anele', 'Gumede', 'seed.contact.anele@example.com', 'Section 18A tax certificate', 'Please send me a Section 18A certificate for my donations this tax year.', 'unread', '2026-10-02 12:30:00+02'),
  ('5eed1105-5eed-4eed-8eed-5eed5eed5eed', 'Werner', 'du Plessis', 'seed.contact.werner@example.com', 'Sponsoring the food garden', 'Our farm can donate seedlings every season. Who should I speak to?', 'archived', '2026-08-05 09:10:00+02'),
  ('5eed1106-5eed-4eed-8eed-5eed5eed5eed', 'Thato', 'Mokoena', 'seed.contact.thato@example.com', 'Bursary information', 'Does TMF offer bursaries for first-year university students?', 'read', '2026-09-15 16:40:00+02'),
  ('5eed1107-5eed-4eed-8eed-5eed5eed5eed', 'Nadia', 'Hendricks', 'seed.contact.nadia@example.com', 'Website feedback', 'The donation page did not load on my phone yesterday evening.', 'unread', '2026-10-07 21:05:00+02'),
  ('5eed1108-5eed-4eed-8eed-5eed5eed5eed', 'Lwazi', 'Dube', 'seed.contact.lwazi@example.com', 'School shoes drive', 'Our church collected 40 pairs of school shoes. Where can we drop them off?', 'unread', '2026-10-04 14:15:00+02'),
  ('5eed1109-5eed-4eed-8eed-5eed5eed5eed', 'Carmen', 'Abrahams', 'seed.contact.carmen@example.com', 'Partnership with our NPO', 'We run a soup kitchen in Eldorado Park and would like to partner on home visits.', 'archived', '2026-07-22 11:00:00+02'),
  ('5eed110a-5eed-4eed-8eed-5eed5eed5eed', 'Musa', 'Khoza', 'seed.contact.musa@example.com', 'Media enquiry', 'I am writing a community newspaper article on Mandela Day projects. Can I interview someone?', 'read', '2026-07-20 08:50:00+02')
on conflict (id) do nothing;

-- 19. reports
insert into public.reports (id, admin_id, report_name, generated_at, report_type, status, metadata) values
  ('5eed1201-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', 'System summary - September 2026', '2026-10-01 07:00:00+02', 'system_summary', 'generated', '{"period": "2026-09", "seed": true}'::jsonb),
  ('5eed1202-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', 'System summary - August 2026', '2026-09-01 07:00:00+02', 'system_summary', 'archived', '{"period": "2026-08", "seed": true}'::jsonb),
  ('5eed1203-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', 'Donations summary - Q3 2026', '2026-10-02 09:00:00+02', 'donations_summary', 'generated', '{"period": "2026-Q3", "seed": true}'::jsonb),
  ('5eed1204-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', 'Donations summary - Q2 2026', '2026-07-02 09:00:00+02', 'donations_summary', 'archived', '{"period": "2026-Q2", "seed": true}'::jsonb),
  ('5eed1205-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', 'Assistance requests - September 2026', '2026-10-01 07:30:00+02', 'assistance_summary', 'generated', '{"period": "2026-09", "seed": true}'::jsonb),
  ('5eed1206-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', 'Volunteer hours - Q3 2026', '2026-10-03 10:00:00+02', 'volunteer_hours', 'generated', '{"period": "2026-Q3", "seed": true}'::jsonb),
  ('5eed1207-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', 'Campaign performance - KZN Flood Relief Appeal', '2026-07-05 12:00:00+02', 'campaign_performance', 'archived', '{"campaign": "KZN Flood Relief Appeal", "seed": true}'::jsonb),
  ('5eed1208-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', 'Sponsorship summary - 2026 to date', '2026-10-05 08:00:00+02', 'sponsorship_summary', 'generated', '{"period": "2026-YTD", "seed": true}'::jsonb),
  ('5eed1209-5eed-4eed-8eed-5eed5eed5eed', '5eed0201-5eed-4eed-8eed-5eed5eed5eed', 'Campaign performance - Winter Blanket Drive 2026', '2026-09-02 12:00:00+02', 'campaign_performance', 'generated', '{"campaign": "Winter Blanket Drive 2026", "seed": true}'::jsonb),
  ('5eed120a-5eed-4eed-8eed-5eed5eed5eed', '5eed0202-5eed-4eed-8eed-5eed5eed5eed', 'Mandela Day impact report', '2026-07-25 15:00:00+02', 'campaign_performance', 'archived', '{"campaign": "Mandela Day Care Packs", "seed": true}'::jsonb)
on conflict (id) do nothing;

do $$ begin raise notice 'seed data applied; run 03_seed_verify.sql next'; end $$;
commit;
