-- TMF Community Support System - M2 "Database ready" seed (03 verify, READ-ONLY)
-- Generated by /workspace/tmf/seed/gen/build.py. All seed ids match the LIKE pattern
--   '5eed____-5eed-4eed-8eed-5eed5eed5eed'  and all seed auth emails match 'seed.%@example.com'.
-- Run order: 01_seed_auth_users.sql -> 02_seed.sql -> 03_seed_verify.sql ; cleanup: 04_seed_cleanup.sql
--
-- ONE SELECT statement: no writes, safe to run in the SQL Editor at any time. One row per check:
-- section | check_name | result (PASS / FAIL / INFO) | detail, plus a SUMMARY row.
-- Seed rows = fixed seed ids, rows owned by seed accounts, and notifications about seed rows.
-- Dynamic per-table/per-constraint counts use query_to_xml (read-only SELECTs).
with pred(tbl, p) as (values
    ('administrator_profiles', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('assistance_requests', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or beneficiary_id in (select id from public.beneficiary_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('beneficiary_profiles', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('campaign_applications', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or volunteer_id in (select id from public.volunteer_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('campaigns', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or admin_id in (select id from public.administrator_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('collection_schedules', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or request_id in (select id from public.assistance_requests where (id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or beneficiary_id in (select id from public.beneficiary_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))))'),
    ('contact_messages', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or email like ''seed.%@example.com'')'),
    ('donation_proofs', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or donation_id in (select id from public.donations where (id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or donor_id in (select id from public.donor_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))))'),
    ('donations', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or donor_id in (select id from public.donor_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('donor_profiles', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('events', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or admin_id in (select id from public.administrator_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('notifications', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or related_entity_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'')'),
    ('profiles', 'id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('reports', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or admin_id in (select id from public.administrator_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('sponsor_profiles', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('sponsorship_request_responses', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or sponsor_id in (select id from public.sponsor_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('sponsorship_requests', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or created_by in (select id from public.administrator_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('sponsorships', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or sponsor_id in (select id from public.sponsor_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('supporting_documents', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or request_id in (select id from public.assistance_requests where (id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or beneficiary_id in (select id from public.beneficiary_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))))'),
    ('user_settings', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('volunteer_assignments', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or volunteer_id in (select id from public.volunteer_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('volunteer_hours', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or volunteer_id in (select id from public.volunteer_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('volunteer_profiles', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''')
),
target(tbl, min_seed, expected_seed) as (values
    ('administrator_profiles', 2, '2'),
    ('assistance_requests', 10, '12'),
    ('beneficiary_profiles', 10, '10'),
    ('campaign_applications', 10, '14'),
    ('campaigns', 10, '12'),
    ('collection_schedules', 10, '10'),
    ('contact_messages', 10, '10'),
    ('donation_proofs', 10, '12'),
    ('donations', 10, '20'),
    ('donor_profiles', 10, '10'),
    ('events', 10, '10'),
    ('notifications', 10, '32 + 10 per non-seed administrator'),
    ('profiles', 10, '42'),
    ('reports', 10, '10'),
    ('sponsor_profiles', 10, '10'),
    ('sponsorship_request_responses', 10, '12'),
    ('sponsorship_requests', 10, '10'),
    ('sponsorships', 10, '12'),
    ('supporting_documents', 10, '12'),
    ('user_settings', 10, '42'),
    ('volunteer_assignments', 10, '10'),
    ('volunteer_hours', 10, '12'),
    ('volunteer_profiles', 10, '10')
),
cnt as (
  select p.tbl,
         (xpath('/row/c/text()', query_to_xml(format('select count(*) as c from public.%I', p.tbl), false, true, '')))[1]::text::int as total,
         (xpath('/row/c/text()', query_to_xml(format('select count(*) as c from public.%I where %s', p.tbl, p.p), false, true, '')))[1]::text::int as seed
  from pred p
),
fks as (
  select c.conname, c.conrelid, c.confrelid, ca.attname as ccol, pa.attname as pcol
  from pg_constraint c
  join pg_attribute ca on ca.attrelid = c.conrelid and ca.attnum = c.conkey[1]
  join pg_attribute pa on pa.attrelid = c.confrelid and pa.attnum = c.confkey[1]
  where c.contype = 'f' and c.connamespace = 'public'::regnamespace
),
orphans as (
  select f.conname, f.conrelid::regclass::text as child, f.ccol, f.confrelid::regclass::text as parent, f.pcol,
         (xpath('/row/c/text()', query_to_xml(format(
            'select count(*) as c from %s x where x.%I is not null and not exists (select 1 from %s y where y.%I = x.%I)',
            f.conrelid::regclass, f.ccol, f.confrelid::regclass, f.pcol, f.ccol), false, true, '')))[1]::text::int as n_orphan,
         case when cp.p is not null and pp.p is not null then
         (xpath('/row/c/text()', query_to_xml(format(
            'select count(*) as c from %s where (%s) and %I is not null and %I not in (select %I from %s where %s)',
            f.conrelid::regclass, cp.p, f.ccol, f.ccol, f.pcol, f.confrelid::regclass, pp.p), false, true, '')))[1]::text::int end as n_seed_to_nonseed,
         case when cp.p is not null and pp.p is not null then
         (xpath('/row/c/text()', query_to_xml(format(
            'select count(*) as c from %s where not (%s) and %I in (select %I from %s where %s)',
            f.conrelid::regclass, cp.p, f.ccol, f.pcol, f.confrelid::regclass, pp.p), false, true, '')))[1]::text::int end as n_nonseed_to_seed
  from fks f
  left join pred cp on f.conrelid = ('public.' || cp.tbl)::regclass
  left join pred pp on f.confrelid = ('public.' || pp.tbl)::regclass
),
checks as (
  select c.conrelid::regclass::text as tbl, c.conname, c.convalidated,
         (xpath('/row/c/text()', query_to_xml(format('select count(*) as c from %s where not (%s)',
            c.conrelid::regclass, regexp_replace(pg_get_constraintdef(c.oid), '^CHECK ', '')), false, true, '')))[1]::text::int as n_bad
  from pg_constraint c where c.contype = 'c' and c.connamespace = 'public'::regnamespace
),
seed_users as (
  select u.*, (u.email in ('seed.admin.thandi.mokoena@example.com', 'seed.admin.pieter.vandermerwe@example.com', 'seed.donor.sipho.ndlovu@example.com', 'seed.donor.ayesha.patel@example.com', 'seed.donor.johan.botha@example.com', 'seed.beneficiary.nosipho.zulu@example.com', 'seed.beneficiary.bongani.mahlangu@example.com', 'seed.beneficiary.precious.sithole@example.com', 'seed.volunteer.kabelo.tau@example.com', 'seed.volunteer.amahle.ngcobo@example.com', 'seed.volunteer.liam.jacobs@example.com', 'seed.sponsor.ubuntu.fresh@example.com', 'seed.sponsor.jozi.build@example.com', 'seed.sponsor.kasi.connect@example.com')) as should_login from auth.users u
  where u.id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' and u.email like 'seed.%@example.com'
),
res(section, check_name, result, detail) as (
  select '1 counts', t.tbl, case when c.seed >= t.min_seed then 'PASS' else 'FAIL' end,
         format('seed rows %s (expected %s, minimum %s); total rows %s', c.seed, t.expected_seed, t.min_seed, c.total)
  from target t join cnt c using (tbl)
  union all
  select '1 counts', 'auth.users (seed accounts)', case when count(*) = 42 then 'PASS' else 'FAIL' end,
         format('%s seed accounts (expected 42), %s login-enabled (expected 14), %s with an email identity',
                count(*), count(*) filter (where encrypted_password <> ''),
                count(*) filter (where exists (select 1 from auth.identities i where i.user_id = seed_users.id and i.provider = 'email')))
  from seed_users
  union all
  select '2 FK orphans', o.conname, case when o.n_orphan = 0 then 'PASS' else 'FAIL' end,
         format('%s.%s -> %s.%s: %s orphan(s)', o.child, o.ccol, o.parent, o.pcol, o.n_orphan) from orphans o
  union all
  select '2 seed isolation', 'seed rows reference only seed rows (notifications: next row)',
         case when coalesce(sum(n_seed_to_nonseed) filter (where conname <> 'notifications_user_id_fkey'), 0) = 0 then 'PASS' else 'FAIL' end,
         coalesce(string_agg(format('%s: %s', conname, n_seed_to_nonseed), ', ')
                  filter (where n_seed_to_nonseed > 0 and conname <> 'notifications_user_id_fkey'), 'none') from orphans
  union all
  select '2 seed isolation', 'seed notifications to non-seed users are only contact alerts to administrators',
         case when count(*) filter (where not (n.related_entity_type = 'contact_messages' and p.role = 'administrator')) = 0 then 'PASS' else 'FAIL' end,
         format('%s contact-message alert(s) delivered to %s non-seed administrator(s) by contact_messages_notify_admins; %s other',
                count(*) filter (where n.related_entity_type = 'contact_messages' and p.role = 'administrator'),
                count(distinct n.user_id) filter (where n.related_entity_type = 'contact_messages' and p.role = 'administrator'),
                count(*) filter (where not (n.related_entity_type = 'contact_messages' and p.role = 'administrator')))
  from (select * from public.notifications where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or related_entity_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed')) n
  join public.profiles p on p.id = n.user_id
  where not (p.id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed')
  union all
  select '2 seed isolation', 'non-seed rows referencing seed rows (cleanup would refuse)', 'INFO',
         coalesce(string_agg(format('%s: %s', conname, n_nonseed_to_seed), ', ') filter (where n_nonseed_to_seed > 0), 'none') from orphans
  union all
  select '3 constraints', k.tbl || '.' || k.conname, case when k.n_bad = 0 and k.convalidated then 'PASS' else 'FAIL' end,
         format('%s violating row(s), validated=%s', k.n_bad, k.convalidated) from checks k
  union all
  select '3 constraints', 'no NOT VALID constraints in public', case when count(*) = 0 then 'PASS' else 'FAIL' end,
         coalesce(string_agg(conname, ', '), 'none') from pg_constraint where connamespace = 'public'::regnamespace and not convalidated
  union all
  select '4 rules', 'campaigns.amount_raised = sum of successful money donations', case when count(*) = 0 then 'PASS' else 'FAIL' end,
         coalesce(string_agg(x.title || ' (' || x.amount_raised || ' vs ' || x.s || ')', '; '), 'all campaigns consistent')
  from (select c.title, c.amount_raised, coalesce((select sum(d.amount) from public.donations d where d.campaign_id = c.id
          and d.donation_kind = 'money' and d.status = 'successful'), 0) as s from public.campaigns c) x where x.amount_raised <> x.s
  union all
  select '4 rules', 'each seed profile has exactly its own role profile', case when count(*) = 0 then 'PASS' else 'FAIL' end,
         coalesce(string_agg(email, ', '), 'all consistent')
  from (select p.email, p.role,
          (select count(*) from public.administrator_profiles where user_id = p.id) a, (select count(*) from public.donor_profiles where user_id = p.id) d,
          (select count(*) from public.beneficiary_profiles where user_id = p.id) b, (select count(*) from public.volunteer_profiles where user_id = p.id) v,
          (select count(*) from public.sponsor_profiles where user_id = p.id) s
        from public.profiles p where p.id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed') r
  where (a + d + b + v + s) <> 1
     or (r.role = 'administrator' and a <> 1) or (r.role = 'donor' and d <> 1) or (r.role = 'beneficiary' and b <> 1)
     or (r.role = 'volunteer' and v <> 1) or (r.role = 'sponsor' and s <> 1)
  union all
  select '4 rules', 'seed role spread', case when string_agg(format('%s=%s', role, n), ' ' order by role)
           = 'administrator=2 volunteer=10 beneficiary=10 donor=10 sponsor=10' then 'PASS' else 'FAIL' end,
         string_agg(format('%s=%s', role, n), ' ' order by role)
  from (select role, count(*) n from public.profiles where id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' group by role) r
  union all
  select '4 rules', 'seed profiles match auth email and have user_settings', case when count(*) = 0 then 'PASS' else 'FAIL' end,
         coalesce(string_agg(p.email, ', '), 'all consistent')
  from public.profiles p left join auth.users u on u.id = p.id
  where p.id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' and (u.email is distinct from p.email or not exists (select 1 from public.user_settings s where s.user_id = p.id))
  union all
  select '4 rules', 'seed auth rows are Auth-safe (no NULL tokens, confirmed, login as planned)',
         case when count(*) filter (where confirmation_token is null or recovery_token is null or email_change_token_new is null
                or email_change is null or email_change_token_current is null or phone_change is null or phone_change_token is null
                or reauthentication_token is null or email_confirmed_at is null or encrypted_password is null
                or (should_login <> (encrypted_password <> ''))) = 0 and count(*) > 0 then 'PASS' else 'FAIL' end,
         format('%s accounts checked', count(*)) from seed_users
  union all
  select '4 rules', 'receipt numbers only on successful seed donations', case when count(*) = 0 then 'PASS' else 'FAIL' end, format('%s violation(s)', count(*))
  from public.donations where receipt_number is not null and status <> 'successful' and (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or donor_id in (select id from public.donor_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'))
  union all
  select '4 rules', 'reviewed seed proofs/requests carry reviewer + time; pending ones do not', case when count(*) = 0 then 'PASS' else 'FAIL' end, format('%s violation(s)', count(*))
  from (select verification_status::text st, reviewed_by, reviewed_at from public.donation_proofs where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or donation_id in (select id from public.donations where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or donor_id in (select id from public.donor_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'))))
        union all
        select case when status = 'pending' then 'pending' else 'reviewed' end, reviewed_by, reviewed_at from public.assistance_requests where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or beneficiary_id in (select id from public.beneficiary_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'))) r
  where (st = 'pending') <> (reviewed_by is null) or (reviewed_by is null) <> (reviewed_at is null)
  union all
  select '4 rules', 'every seed contact message notified >= 1 administrator', case when count(*) = 0 then 'PASS' else 'FAIL' end,
         coalesce(string_agg(subject, '; '), 'all notified')
  from public.contact_messages m where m.id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'
    and not exists (select 1 from public.notifications n where n.related_entity_type = 'contact_messages' and n.related_entity_id = m.id)
)
select section, check_name, result, detail from res
union all
select 'SUMMARY', 'RESULTS', case when count(*) filter (where result = 'FAIL') = 0 then 'PASS' else 'FAIL' end,
       format('PASS=%s FAIL=%s INFO=%s', count(*) filter (where result = 'PASS'), count(*) filter (where result = 'FAIL'), count(*) filter (where result = 'INFO'))
from res
order by 1, 2;
