-- TMF Community Support System - M2 "Database ready" seed (04 cleanup)
-- Generated by /workspace/tmf/seed/gen/build.py. All seed ids match the LIKE pattern
--   '5eed____-5eed-4eed-8eed-5eed5eed5eed'  and all seed auth emails match 'seed.%@example.com'.
-- Run order: 01_seed_auth_users.sql -> 02_seed.sql -> 03_seed_verify.sql ; cleanup: 04_seed_cleanup.sql
--
-- Removes ONLY seed rows: fixed seed ids, rows owned by the 42 seed accounts (incl. later test
-- activity), notifications about seed rows, and the seed auth users (id pattern AND seed email).
-- It never deletes or edits other data: if any NON-seed row references a seed row (e.g. a real
-- volunteer applied to a seed campaign), it aborts and lists them. Set v_force to true below only
-- after reviewing that list (FK cascades / SET NULL would then touch those rows).
-- Files uploaded to Storage by seed accounts are not removed by SQL (delete them in Storage).
-- Idempotent: a second run deletes nothing.
begin;

do $$
declare
  v_force constant boolean := false;
  r record; v_n int; v_report text := '';
begin
  for r in
    with pred(tbl, p) as (values
    ('administrator_profiles', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('assistance_requests', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or beneficiary_id in (select id from public.beneficiary_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('beneficiary_profiles', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('campaign_applications', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or volunteer_id in (select id from public.volunteer_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('campaigns', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or admin_id in (select id from public.administrator_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('collection_schedules', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or request_id in (select id from public.assistance_requests where (id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or beneficiary_id in (select id from public.beneficiary_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))))'),
    ('contact_messages', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or email like ''seed.%@example.com'')'),
    ('donation_proofs', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or donation_id in (select id from public.donations where (id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or donor_id in (select id from public.donor_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))))'),
    ('donations', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or donor_id in (select id from public.donor_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('donor_profiles', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('events', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or admin_id in (select id from public.administrator_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('notifications', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or related_entity_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'')'),
    ('profiles', 'id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('reports', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or admin_id in (select id from public.administrator_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('sponsor_profiles', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('sponsorship_request_responses', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or sponsor_id in (select id from public.sponsor_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('sponsorship_requests', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or created_by in (select id from public.administrator_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('sponsorships', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or sponsor_id in (select id from public.sponsor_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('supporting_documents', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or request_id in (select id from public.assistance_requests where (id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or beneficiary_id in (select id from public.beneficiary_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))))'),
    ('user_settings', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'''),
    ('volunteer_assignments', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or volunteer_id in (select id from public.volunteer_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('volunteer_hours', '(id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed'' or volunteer_id in (select id from public.volunteer_profiles where user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''))'),
    ('volunteer_profiles', 'user_id::text like ''5eed____-5eed-4eed-8eed-5eed5eed5eed''')
    )
    select c.conname, c.conrelid::regclass as child, ca.attname as ccol, c.confrelid::regclass as parent, pa.attname as pcol,
           cp.p as cpred, pp.p as ppred
    from pg_constraint c
    join pg_attribute ca on ca.attrelid = c.conrelid and ca.attnum = c.conkey[1]
    join pg_attribute pa on pa.attrelid = c.confrelid and pa.attnum = c.confkey[1]
    join pred cp on c.conrelid = ('public.' || cp.tbl)::regclass
    join pred pp on c.confrelid = ('public.' || pp.tbl)::regclass
    where c.contype = 'f' and c.connamespace = 'public'::regnamespace
  loop
    execute format('select count(*) from %s where not (%s) and %I in (select %I from %s where %s)',
                   r.child, r.cpred, r.ccol, r.pcol, r.parent, r.ppred) into v_n;
    if v_n > 0 then v_report := v_report || format('%s (%s.%s): %s; ', r.conname, r.child, r.ccol, v_n); end if;
  end loop;
  if v_report <> '' and not v_force then
    raise exception 'Non-seed rows reference seed rows - nothing deleted. Review: %', v_report;
  elsif v_report <> '' then
    raise notice 'v_force = true: proceeding although non-seed rows reference seed rows: %', v_report;
  end if;
end $$;

-- Non-seed campaigns that received seed-owned donations (test activity) get amount_raised
-- recomputed after the delete (the donations trigger does not fire on DELETE).
create temporary table _seed_touched_campaigns on commit drop as
  select distinct campaign_id from public.donations
  where campaign_id is not null and (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or donor_id in (select id from public.donor_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'))
    and campaign_id not in (select id from public.campaigns where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or admin_id in (select id from public.administrator_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed')));

delete from public.notifications where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or related_entity_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed');
delete from public.contact_messages where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or email like 'seed.%@example.com');
delete from public.reports where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or admin_id in (select id from public.administrator_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'));
delete from public.volunteer_hours where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or volunteer_id in (select id from public.volunteer_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'));
delete from public.volunteer_assignments where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or volunteer_id in (select id from public.volunteer_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'));
delete from public.campaign_applications where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or volunteer_id in (select id from public.volunteer_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'));
delete from public.collection_schedules where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or request_id in (select id from public.assistance_requests where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or beneficiary_id in (select id from public.beneficiary_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'))));
delete from public.supporting_documents where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or request_id in (select id from public.assistance_requests where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or beneficiary_id in (select id from public.beneficiary_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'))));
delete from public.assistance_requests where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or beneficiary_id in (select id from public.beneficiary_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'));
delete from public.donation_proofs where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or donation_id in (select id from public.donations where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or donor_id in (select id from public.donor_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'))));
delete from public.donations where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or donor_id in (select id from public.donor_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'));
delete from public.sponsorship_request_responses where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or sponsor_id in (select id from public.sponsor_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'));
delete from public.sponsorships where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or sponsor_id in (select id from public.sponsor_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'));
delete from public.sponsorship_requests where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or created_by in (select id from public.administrator_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'));
delete from public.events where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or admin_id in (select id from public.administrator_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'));
delete from public.campaigns where (id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' or admin_id in (select id from public.administrator_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'));
delete from public.user_settings where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed';
delete from public.donor_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed';
delete from public.beneficiary_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed';
delete from public.volunteer_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed';
delete from public.sponsor_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed';
delete from public.administrator_profiles where user_id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed';
delete from public.profiles where id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed';
delete from auth.identities where user_id in (select id from auth.users where id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' and email like 'seed.%@example.com');
delete from auth.users where id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed' and email like 'seed.%@example.com';

select public.update_campaign_amount_raised(campaign_id) from _seed_touched_campaigns;

do $$ begin
  raise notice 'cleanup done; remaining seed auth users: %, seed profiles: %',
    (select count(*) from auth.users where id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed'), (select count(*) from public.profiles where id::text like '5eed____-5eed-4eed-8eed-5eed5eed5eed');
end $$;
commit;
